### ISSUE TITLE
Save All Sources does not work, zip file is not created

### ISSUE THREAD

**Issue by joehni** [java-decompiler/jd-gui#1]
"Save All Sources" does not work with 1.0.0-RC1. After the location of the zip file has been chosen, the dialog with the progress bar appears, but nothing happens anymore. No progress at all and the close button does not react. jd-gui did create a temporary zip file in the temp directory, but the file size stays at 22 bytes and unzip reports that it is empty. It is possible to close the dialog using the close button of the window manager though.

I tried Java 7 and Java 8 as runtime executed on a 64-bit Linux.

**Comment by emmanue1** [comment]
Fixed
