### ISSUE TITLE
Code displayed as error

### ISSUE THREAD

**Issue by brentil** [java-decompiler/jd-gui#10]
I'm not sure if this is an issue in the JD-core or what, I didn't know where else to report it.  In the last version and here now too in 1.0 I have 2 classes that show like this.

    /* Error */
    public void run()
    {
      // Byte code:
      //   0: aload_0

I have no idea why there's being shown the error though.

**Comment by emmanue1** [comment]
It looks like an issue in JD-Core. Could you send your CLASS file by mail to java.decompiler at gmail.com? I cant promise to fix it quickly : I'm focus on publishing JD projects on GitHub.

**Comment by brentil** [comment]
I sent the code the other day, I just forgot to update here.
