### ISSUE TITLE
Incorrect result in static setters

### ISSUE THREAD

**Issue by jiaminglu** [java-decompiler/jd-gui#102]
Static member variables should be referenced by its qualified name, i.e. "MyClass.mMember" instead of just "mMember".

Source:

``` java
package test;
public class test {
    static String hello;
    public static void setHello(String hello) {
        test.hello = hello;
    }
}
```

Decompiled result:

``` java
package test;
public class test {
    static String hello;
    public static void setHello(String hello) {
       hello = hello;
    }
}
```

The jar file:
[test.jar.zip](https://github.com/java-decompiler/jd-gui/files/59019/test.jar.zip)

Version:
1.4.0, java version 1.8.0_45

**Comment by emmanue1** [comment]
Fixed.
2015 -> I close this issue.
