### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by samczsun** [java-decompiler/jd-gui#106]
Hello,

What is JD-Core licensed under? Is it GPLv3 or All Rights Reserved?

Furthermore, may I suggest licensing your project under Apache 2.0? You'll find that the majority of projects are licensed via Apache 2.0 as GPLv3 is much more restrictive and infectious.

Regards.

**Comment by theuserbl** [comment]
Here the answert for you:

At
https://plus.google.com/107508651694381167848
the author writes

> JD-Core project will be under the GPLv3 license, eventually. The project was born in 2007. Before opening the sources, a refactoring should be done. Today, you can:
> - use jd-core-0.7.1.jar stored on GitHub
> - decompile my decompiler !! :)
> - take a look on the excellent projects  https://github.com/fesh0r/fernflower and https://bitbucket.org/mstrobel/procyon

And at
https://github.com/java-decompiler/jd-gui/blob/master/NOTICE
stands

> JD-Core Java Release - GPLv3

So, to combine all the informations:
- The sourcecode is currently not published, but will be in the future
- It is already under the GPLv3
- It is allowed to decompile the source.

=> So you can decompile JD-Core and publish the decompilation under the GPLv3.
To create the header-files on Unix, you can use this scripts:
https://github.com/java-decompiler/jd-gui/issues/104


Similar situation exists with the CFR-Decompiler (http://www.benf.org/other/cfr/):
As you can read there in the FAQ
http://www.benf.org/other/cfr/faq.html
the binary is already published under the MIT-license, the sources will be in this current state not publiched, but it is allowed to decompile.

**Comment by emmanue1** [comment]
@samczsun, I send you a response this weekend. @theuserbl, thanks for your alert.
