### ISSUE TITLE
Webside down

### ISSUE THREAD

**Issue by theuserbl** [java-decompiler/jd-gui#107]
At first I thought, it is only temporary. But now it seems that the webside http://jd.benow.ca/ is a longer time down or will never come back.

So, this post is for all, who miss the webside.
### Archived Webside

You can find the last archived version at
http://web.archive.org/web/20151117140416/http://jd.benow.ca/
For Windows existing additional an independent webside, which uses some components of the original webside:
http://domoticx.com/java-decompiler-jd-gui-jar-class-bestanden/

The Google+ side of JD, which is linked on the webside,  you can find at
https://plus.google.com/107508651694381167848
### Links to Java/Groovy written, JVM-based versions

You can find everytime the latest version at
https://github.com/java-decompiler/jd-gui/releases

As I write this text, the latest version was 1.4.0.

The Java-version for all plattforms of JD-GUI 1.4.0:
[jd-gui-1.4.0.jar](https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui-1.4.0.jar)

The Linux-version of JD-GUI 1.4.0:
[jd-gui-1.4.0-0.noarch.rpm](https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui-1.4.0-0.noarch.rpm)
[jd-gui_1.4.0-0_all.deb](https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui_1.4.0-0_all.deb)

The Mac-version of JD-GUI 1.4.0:
[jd-gui-osx-1.4.0.tar](https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui-osx-1.4.0.tar)

The Windows-version of JD-GUI 1.4.0:
[jd-gui-windows-1.4.0.zip](https://github.com/java-decompiler/jd-gui/releases/download/v1.4.0/jd-gui-windows-1.4.0.zip)

The source code of JD-GUI 1.4.0:
[Source code (zip)](https://github.com/java-decompiler/jd-gui/archive/v1.4.0.zip)
[Source code (tar.gz)](https://github.com/java-decompiler/jd-gui/archive/v1.4.0.tar.gz)
### Archived C++ compiled binaries

The archived 32bit JD-GUI-binaries written in C++ with WxWidgets 2.8:

Linux version of JD-GUI 0.3.5:
[jd-gui-0.3.5.linux.i686.tar.gz](http://web.archive.org/web/20151117140416/http://jd.benow.ca/jd-gui/downloads/jd-gui-0.3.5.linux.i686.tar.gz) (from web.archive.org)
[jd-gui-0.3.5.linux.i686.tar.gz.zip](https://github.com/java-decompiler/jd-gui/files/72673/jd-gui-0.3.5.linux.i686.tar.gz.zip) (github-hosted)

Mac version of JD-GUI 0.3.5:
[jd-gui-0.3.5.osx.i686.dmg](http://web.archive.org/web/20151117140416/http://jd.benow.ca/jd-gui/downloads/jd-gui-0.3.5.osx.i686.dmg) (from web.archive.org)
[jd-gui-0.3.5.osx.i686.dmg.zip](https://github.com/java-decompiler/jd-gui/files/72674/jd-gui-0.3.5.osx.i686.dmg.zip) (github-hosted)

Windows version of JD-GUI 0.3.5:
[jd-gui-0.3.5.windows.zip](http://web.archive.org/web/20151117140416/http://jd.benow.ca/jd-gui/downloads/jd-gui-0.3.5.windows.zip) (from web.archive.org)
[jd-gui-0.3.5.windows.zip](https://github.com/java-decompiler/jd-gui/files/72670/jd-gui-0.3.5.windows.zip) (github-hosted)
[jd-gui-0.3.5.windows.7z](http://domoticx.phoenixinteractive.nl/software/jdgui/jd-gui-0.3.5.windows.7z) (phoenixinteractive hosted)

Windows version of JD-GUI 0.3.6:
[jd-gui-0.3.6.windows.zip](http://web.archive.org/web/20151117140416/http://jd.benow.ca/jd-gui/downloads/jd-gui-0.3.6.windows.zip) (from web.archive.org)
[jd-gui-0.3.6.windows.zip](https://github.com/java-decompiler/jd-gui/files/72671/jd-gui-0.3.6.windows.zip) (github-hosted)
[jd-gui-0.3.6.windows.7z](http://domoticx.phoenixinteractive.nl/software/jdgui/jd-gui-0.3.6.windows.7z) (phoenixinteractive hosted)

Windows version of JD-GUI 0.3.7-RC-1:
[jd-gui-0.3.7-RC-1.windows.zip](https://github.com/java-decompiler/jd-gui/files/72672/jd-gui-0.3.7-RC-1.windows.zip) (github-hosted)
[jd-gui-0.3.7-RC-1.windows.7z](http://domoticx.phoenixinteractive.nl/software/jdgui/jd-gui-0.3.7-RC-1.windows.7z) (phoenixinteractive hosted)

**Comment by theuserbl** [comment]
Only for people, who are interested in it, the last archived old homepage:
http://web.archive.org/web/20130513040159/http://java.decompiler.free.fr/
But that is only for JD-GUI fans :smile:

**Comment by UlyssesWu** [comment]
Websi**t**e ? :P

**Comment by yyyjajp** [comment]
available at http://java-decompiler.github.io/
