### ISSUE TITLE
Incorrect decompile of LocalVariable entities sharing common stack index

### ISSUE THREAD

**Issue by wins0049** [java-decompiler/jd-gui#108]
I found an incorrect behavior in the decompiler where undeclared local variables can be incorrectly decompiled when they share a common storage index as one of the declared local variables.  I created a simple example below by setting up a couple IF statements in parallel.  The short story is that the decompiler needs to pay closer attention to the start/end scope labels for local variables.  For more details see my description below.

See the example code below.  Notice how `testInt2` is at the end of the second IF statement.  This means that the Java compiler will not add a LocalVariable definition for this entity.  Notice also that looking at the entire scope of this method you'll see that testString2 has a stack index of `3` (you can see this in the bytecode further down.)  Variable `testInt2` also has a stack index of `3` but it doesn't have a LocalVariable defined in the bytecode since it is located at the end of its scope.  (you can see `testInt2` stored at index `3` in the bytecode representation below).

``` Java
    public void TEST2() {
        boolean testBoolean = true;
        if (testBoolean) {
            String testString1 = "NTEW";
            String testString2 = "UWHG";
            String testString3 = "VDWV";
        }
        if (testBoolean) {
            int testInt1 = 658;
            int testInt2 = 521;
        }
    }
```

After compiling into a class and feeding that class into the decompiler it becomes represented as the following.  Notice that `String testString2;` initialization is now pulled outside the first IF statement and incorrectly used as the variable for testInt2.

``` Java
  public void TEST2()
  {
    boolean testBoolean = true;
    String testString2;
    if (testBoolean)
    {
      String testString1 = "NTEW";
      testString2 = "UWHG";
      String str1 = "VDWV";
    }
    if (testBoolean)
    {
      int testInt1 = 658;
      testString2 = 521;
    }
  }
```

Below is the java bytecode representation that creates this method.  Notice that `testString2` has a scope defined in its LocalVariable definition as starting at label L5 and ending at label L2 so it should not be accessible by the second IF statement.

```
  // access flags 0x1
  public TEST2()V
   L0
    LINENUMBER 133 L0
    ICONST_1
    ISTORE 1
   L1
    LINENUMBER 134 L1
    ILOAD 1
    IFEQ L2
   L3
    LINENUMBER 135 L3
    LDC "NTEW"
    ASTORE 2
   L4
    LINENUMBER 136 L4
    LDC "UWHG"
    ASTORE 3
   L5
    LINENUMBER 137 L5
    LDC "VDWV"
    ASTORE 4
   L2
    LINENUMBER 139 L2
   FRAME APPEND [I]
    ILOAD 1
    IFEQ L6
   L7
    LINENUMBER 140 L7
    SIPUSH 658
    ISTORE 2
   L8
    LINENUMBER 141 L8
    SIPUSH 521
    ISTORE 3
   L6
    LINENUMBER 143 L6
   FRAME SAME
    RETURN
   L9
    LOCALVARIABLE this Lasm/AGENT_1; L0 L9 0
    LOCALVARIABLE testBoolean Z L1 L9 1
    LOCALVARIABLE testString1 Ljava/lang/String; L4 L2 2
    LOCALVARIABLE testString2 Ljava/lang/String; L5 L2 3
    LOCALVARIABLE testInt1 I L8 L6 2
    MAXSTACK = 1
    MAXLOCALS = 5
}
```

If you could fix this it would be greatly appreciated as it can be very confusing when seeing this behavior on more complex code segments.

**Comment by emmanue1** [comment]
Try the last release, please.
2015 -> I close this issue.
