### ISSUE TITLE
Decompiler core 0.7.1 fails to decompile three methods within a class file - worked previously under 0.7.01

### ISSUE THREAD

**Issue by robbinma4** [java-decompiler/jd-gui#109]
Hello,

the decompiler core is having problems decompiling the attached class.
In particular the following methods:
changeStatus
updateIsRunningForRP
insertIsRunningForRP

It identifies the method name and parameters correctly but it then inserts comments with the associated pcode in the method body.

The previous version of the decompiler was able to decompile these methods correctly and populate them with the correct code.

Could you have a look at this problem please.

thanks for a really useful tool.

best regards.
[VFMPlusPSR.zip](https://github.com/java-decompiler/jd-gui/files/79552/VFMPlusPSR.zip)

**Comment by emmanue1** [comment]
Fixed (so late, sorry).
