### ISSUE TITLE
Internal error display on windows with v1.4.0, not with 0.3.6

### ISSUE THREAD

**Issue by hgiritzer** [java-decompiler/jd-gui#110]
See org.alljoyn.bus.AuthListener.class and BusAttachment.class of file:
[alljoyn.zip](https://github.com/java-decompiler/jd-gui/files/95196/alljoyn.zip)

**Comment by samrocketman** [comment]
Reproduced on Mac OS X as well using `java -jar jd-gui-1.4.0.jar`.

**Comment by emmanue1** [comment]
Fixed (so late, sorry)
