### ISSUE TITLE
No code on JD on class with compiled with 1.8.0

### ISSUE THREAD

**Issue by vmsv** [java-decompiler/jd-gui#111]
I've seen that is not confirmed that 1.8.0 is supported. So no code is normal when the class is compiled with 1.8.0 or above?

**Comment by theuserbl** [comment]
Have you tried to decompile a jar-file or a class-file in a directory?
First one works. Last one not. And if you try at first the last one, then the first one will not working, too, until an restart of JD-GUI.

**Comment by emmanue1** [comment]
Try the last release, please.
2016 -> I close this issue.
