### ISSUE TITLE
JD GUI author disappeared without a trace.

### ISSUE THREAD

**Issue by theuserbl** [java-decompiler/jd-gui#119]
I thought long enogh about it, if I should post this as issue. But now I deciuded, to do so.

The JD GUI author Emmanuel Dupuy seems to be disappeared without a trace.

Long time, there comes steadily updates on its JD-GUI main side.
Later it moves over to https://plus.google.com/107508651694381167848
On mid 2015 he published JD-GUI here on github as OpenSource. And so his activity goes on here.

Every month he posted at minimum one commit:
https://github.com/java-decompiler/jd-gui/commits/master
But Sep 2, 2015 comes his last commit.

Beside committing, he also comment issues. The last two comments are on 6 Oct 2015 (https://github.com/java-decompiler/jd-gui/issues/86) and 26 Oct 2015 (https://github.com/java-decompiler/jd-gui/pull/88)

After that, all activity of the author ends abruptly.

Then there comes the xmas holiday in december 2015. Most projects have then its most active time. But JDs activity was zero.

Nearly five month after the last activity of the author in 2015, there is still silence.

So I decided to open the issue, that the author is disappeared without a trace.
If he is still there, he can close this issue.
Otherwise it stays open for all time.

**Comment by emmanue1** [comment]
I reply tomorrow, ok?

Date: Thu, 17 Mar 2016 09:20:41 -0700

**Comment by emmanue1** [comment]
Hi all, 

I'm alive ! I spend my time to creating a new major release of JD-Core.
The JD-Core 0.x project started in 2007. Its maintenance is a nightmare today.

JD-Core 1.0 will be:
- rewritten from scratch in Java
- more effective with Java8
- easier to maintain
- more tested
- more modular.

The most complex design problem are solved. 70% of development have been made. The project will be shared on GitHub.

Emmanuel.

**Comment by samrocketman** [comment]
Great @emmanue1.  I appreciate your work.

**Comment by theuserbl** [comment]
@samrocketman: If you click on http://jd.benow.ca/ under the JD-GUI-, JD-Eclipse- or JD-IntelliJ-title on the "Download"-tab, you see on the right side a donation button.

Btw: Personally I hope, that emmanue1 and samczsun findig together a solution for the licensing problems, which samczsun have:
https://github.com/java-decompiler/jd-gui/issues/106
https://github.com/samczsun/Helios/issues/2
https://github.com/samczsun/Helios

**Comment by samrocketman** [comment]
Thanks @theuserbl

**Comment by soumali** [comment]
Thanks @emmanue1 @theuserbl . Can you confirm, if you will come out with a command line version for jd-core ? Many people would like to use it without GUI

**Comment by java-decompiler** [comment]
Hi. Once JD-Core 1.0 is released, it'll be a piece of cake.

2016-07-07 15:46 GMT+02:00 soumali <notifications@github.com>:

**Comment by emmanue1** [comment]
Hi. Once JD-Core 1.0 is released, it'll be a piece of cake.

**Comment by soumali** [comment]
Thanks a lot for your reply, do u have any tentative date by when it would be available?

**Comment by don-vip** [comment]
@emmanue1 are you still out there? Any news from this new JD-Core project?

**Comment by javorsh** [comment]
Since jd-gui version 0.3.6 , in current versions there is 1 wrong annoying  issue - when try to open some class file from windows folder of existing  project (set auto open with jd-gui) ->  this class file is not auto position and decompiled  in jd-window pane . Now The window pane is blank, in left pane is folder structure of whole project .
