### ISSUE TITLE
Problem with ./gradlew build

### ISSUE THREAD

**Issue by winxungphong** [java-decompiler/jd-gui#123]
I follow the guide for Terminal on mac, then get failure result after the first guide. 
`jd-gui-master minhht$ ./gradlew build --stacktrace
:distTar UP-TO-DATE
:distZip UP-TO-DATE
:doFirstDistTar UP-TO-DATE
:doFirstDistZip UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:api:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':api:compileJava'.
  > invalid source release: 1.7
  `
  I need solution for this, thank in advance!

**Comment by samrocketman** [comment]
Are you building with Java 1.6 or lower?

**Comment by emmanue1** [comment]
Try the last release, please.
2016 -> I close this issue.
