### ISSUE TITLE
Make the Mac app take files as parameter

### ISSUE THREAD

**Issue by sgandon** [java-decompiler/jd-gui#13]
Hello,
I love the jd project, but I wish I could open the jar files from the Mac finder directly by double clicking on it.
But when I associated tje .jar with the JD-GUI.app, and try to open a jar, it brings the app to front but do nothing. Does not open the jar in the app.
This would be great.

 By the way I cannot find the online decompiler, did you remove it ?

**Comment by emmanue1** [comment]
Hi, the online compiler has been disabled. It was hosted on an old Mac Mini PowerPC G4. Impossible to update the JRE 1.5, while the next version of JD-Core could be based on Java 7+ and Groovy.

**Comment by sgandon** [comment]
Thanks Emmanuel.
