### ISSUE TITLE
Decompilation of classes with lambda expression failure

### ISSUE THREAD

**Issue by mistriel** [java-decompiler/jd-gui#133]
Hi,

I'm getting  : 
// INTERNAL ERROR //

On classes that uses lambda expressions .
Jd-Gui 1.4.0

**Comment by TheWinuXs** [comment]
Send your class in http://hastebin.com/ ;)

**Comment by samrocketman** [comment]
Or just use gist.

**Comment by davidmichaelkarr** [comment]
I'm seeing this in all of our classes with lambdas.  Other classes, even in the same package, work fine.  I tried using the "fernflower" decompiler, and it doesn't have this symptom.

**Comment by emmanue1** [comment]
New JD-Core 1.0 is coming with Java 8+, lambda, local method class, try-with-resources statement, default method support.

**Comment by emmanue1** [comment]
JD-Core 1.0.0 support lambda expressions. You can test a preview on http://java-decompiler.github.io.
![image](https://user-images.githubusercontent.com/11559196/54723464-eeb40280-4b67-11e9-9f4b-80b5ca617a7d.png)

**Comment by mistriel** [comment]
Great work pal !
