### ISSUE TITLE
Internal error with lucene-core-6.1.0.jar > Lucene54DocValuesConsumer.class

### ISSUE THREAD

**Issue by OlivierJaquemet** [java-decompiler/jd-gui#140]
The following exceptions occurs when trying to extract `lucene-core-6.1.0.jar` .

To reproduce : 
- Download `lucene-6.1.0.zip` from http://apache.crihan.fr/dist/lucene/java/6.1.0/ 
- Unzip jar `lucene-6.1.0\core\lucene-core-6.1.0.jar` in the archive
- Open jar in JD-GUI
- Browse to class `org\apache\lucene\codecs\lucene54\Lucene54DocValuesConsumer.class`

Tested with JD-GUI 1.4.

![jd-gui-lucene](https://cloud.githubusercontent.com/assets/618861/17548405/0eeb7846-5eec-11e6-9e60-d61fb8ab0a2f.png)

I suspect an issue with the lucene jar / class / source because Dependency Finder (https://github.com/jeantessier/dependency-finder/) also fails to open the same class.
I have also entered an issue on the Dependency Finder project :
https://github.com/jeantessier/dependency-finder/issues/2

Could it be related to this code and the corresponding byte code ?
https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.1.0/lucene/core/src/java/org/apache/lucene/codecs/lucene54/Lucene54DocValuesConsumer.java#L703

**Comment by OlivierJaquemet** [comment]
Same error occurs for class `org\apache\lucene\util\AttributeImpl.class` in same `lucene-core-6.1.0.jar` 

Corresponding source file : 
https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.1.0/lucene/core/src/java/org/apache/lucene/util/AttributeImpl.java

![image](https://cloud.githubusercontent.com/assets/618861/17548865/2057fb20-5eee-11e6-861b-6394499ddbb3.png)

**Comment by JonathanxD** [comment]
Jd gui doens't decompile classes that contains invokedynamic instruction. (lambda expresions)

**Comment by OlivierJaquemet** [comment]
@JonathanxD Thanks for your answer and explanation. 

Any technical limit of a product is fine as long as the end user is made aware of such limitation. 
Thus if this limit cannot be overcome, displaying a more user friendly message would certainly be better than the cryptic `// INTERNAL ERROR //` message.
Something like "This class contains invokedDynamic instruction which are not yet supported", especially as JD does not provide any advanced log window that could otherwise give more detail on the error.

**Comment by JustGregory** [comment]
My question would be whether invokedynamic invalidates decompilation of the *whole* class, or whether the class' other parts can be decompiled around it, leaving a comment block where such errata would be?

**Comment by JonathanxD** [comment]
@JustGregory Invokedynamic doens't invalidates the decompilation. Other decompilers that doens't supports invokedynamic decompile other parts and comment invokedynamic block. The possible cause of the error is because jdgui don't know the byte sequence of invokedynamic and don't know what bytes is part of invokedynamic and that is not.

Sorry for my bad english. :(

**Comment by OlivierJaquemet** [comment]
The similar issue in Dependency Finder was fixed, you may want to look at the corresponding commit for hints ont how to parse specific byte code : 
https://github.com/jeantessier/dependency-finder/commit/945980680efd41074e6ba1dca1c34082380e7e7b

**Comment by emmanue1** [comment]
Fix.
![image](https://user-images.githubusercontent.com/11559196/60565294-49fab100-9d63-11e9-8d9e-ab59f965aa60.png)

**Comment by OlivierJaquemet** [comment]
Thank you @emmanue1 👍🏻
