### ISSUE TITLE
JD-Gui is not supporting HiDpi resolution

### ISSUE THREAD

**Issue by juherr** [java-decompiler/jd-gui#145]
On Windows 10, with HiDpi screen (resolution 3200x1800) and ratio 250% (recommended value), JD-Gui is looking strange.

Icons are too small and classes are overlapping in the tree view.

Check by yourself:

![image](https://cloud.githubusercontent.com/assets/254697/18644667/8d8fce58-7eaa-11e6-86f9-1e14c7f37bd5.png)

**Comment by michalrames** [comment]
Hi @juherr, I was able to resolve (work around) the issue by setting the "Override high DPI scaling behaviour. Scaling performed by:" to **System** or  **System - enhanced**

**Comment by emmanue1** [comment]
Java 8 does not support high DPI. From Java 9, it's supported. You can add "-Dsun.java2d.uiScale=1.5", "-Dsun.java2d.uiScale=2", "-Dsun.java2d.uiScale=2.5" on command line.

**Comment by spottedmahn** [comment]
[using @michalrames "answer"](https://github.com/java-decompiler/jd-gui/issues/145#issuecomment-391597004), thanks Michal!

![java decompile high dpi](https://user-images.githubusercontent.com/14079228/77831347-ef7d5e00-7104-11ea-97fd-99d1c1fba56c.gif)

**Comment by ajayprovar** [comment]
> [using @michalrames "answer"](https://github.com/java-decompiler/jd-gui/issues/145#issuecomment-391597004), thanks Michal!
> 
> ![java decompile high dpi](https://user-images.githubusercontent.com/14079228/77831347-ef7d5e00-7104-11ea-97fd-99d1c1fba56c.gif)

works like a charm!! thanks!!

**Comment by ajaylamba-provar** [comment]
> Hi @juherr, I was able to resolve (work around) the issue by setting the "Override high DPI scaling behaviour. Scaling performed by:" to **System** or **System - enhanced**

Works like a charm, thanks!!
