### ISSUE TITLE
Cannot open in Mac OSX Sierra

### ISSUE THREAD

**Issue by IbraTq** [java-decompiler/jd-gui#146]
Like title, i cannot use jd-gui in my macbook. Please help me.
Here is a log:

Process:               jd-gui [10036]
Path:                  /Applications/JD-GUI.app/Contents/MacOS/jd-gui
Identifier:            jd.jd-gui
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           jd-gui [10036]
User ID:               501

Date/Time:             2016-09-22 11:28:18.416 +0700
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        1611245A-06D9-C16E-B5A3-A2BCF51CC12C

Sleep/Wake UUID:       B23BDF91-F082-46BA-9EB3-99D558FC4472

Time Awake Since Boot: 39000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000241499f5
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x248b8b5b  ebx: 0xbffffa34  ecx: 0x241499f5  edx: 0x00000001
  edi: 0xbffffa9c  esi: 0x00000000  ebp: 0xbffff9f8  esp: 0xbffff9b0
   ss: 0x00000023  efl: 0x00010297  eip: 0x000011bb   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x241499f5
  
Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 26791
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro11,4, BootROM MBP114.0172.B09, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.29f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533642465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.21.171.10.1a16)
Bluetooth: Version 5.0.0f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by IbraTq** [comment]
Thanks you. 
I resolved, just install the latest jd-gui one.

**Comment by GavinSheng** [comment]
Now i Cannot open in Mac OSX 10.12.3 ,which one is ok?

**Comment by kongtianxintang** [comment]
me too! can you help me?
