### ISSUE TITLE
Does not launches on Windows 10

### ISSUE THREAD

**Issue by GouravS** [java-decompiler/jd-gui#148]
Hi,

I'm trying to use it on Windows 10 but it does not even launch. Nothing happens when you click on the shortcut or on the application directly.

Any other way to get it work?

Thanks,
Gourav

**Comment by samrocketman** [comment]
Launch it with `java -jar jd-gui.jar`

**Comment by GouravS** [comment]
Hi Sam,

I get the following error:
"Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object"

THanks,
Gourav

**Comment by VTCAKAVSMoACE** [comment]
You should probably try reinstalling Java. Looks like the installation is broken.

**Comment by GouravS** [comment]
Had similar issue launching Spring Suite where changing VM arguments in the ini file helped but there is no ini file here.

**Comment by VTCAKAVSMoACE** [comment]
Reinstall Java. :P

**Comment by BrunoDM2943** [comment]
@GouravS, reinstalling JVM will fix it! java/lang/Objcet is native class, so, there is an error in your installation. BTW, could you attach your jd-gui.jar here? I may test the execution and prove it to you

**Comment by GouravS** [comment]
Attached the jar file. Thanks!
[jd-gui-1.4.0.jar.zip](https://github.com/java-decompiler/jd-gui/files/528315/jd-gui-1.4.0.jar.zip)

**Comment by BrunoDM2943** [comment]
There's no problem with this jar here. I started the application normally! Seens like its your JVM

**Comment by GouravS** [comment]
Yup,thanks guys. Just reinstalled and its fine. Thanks again!!
