### ISSUE TITLE
foreach statements

### ISSUE THREAD

**Issue by exatoa** [java-decompiler/jd-gui#154]
I compared decompile result with original source code.

I found this:

```
<original code>
String[] wordList = somestring.split();
for (String word: wordList){
     ....
}
```

```
<decompiled code>
String[] wordList = somestring.split();
String[] arrayOfString1; 
int j = (arrayOfString1 = splitWords).length; 
for (int i = 0; i < j; i++) {
    String word = arrayOfString1[i];
    ....
}
```

This is the seond case:

```
<original code>
ArrayList<datatype> list = something;
for(datatype item : list) {
     .....
}
```

```
<decompiled code>
Iterator localIterator3; 
for (Iterator localIterator2 = list.iterator(); localIterator2.hasNext(); localIterator3.hasNext()) 
{
    datatype bug = (datatype)localIterator2.next();
    ....
}
```

Because of this differences, local variable conflicts sometimes.
For example, the variable j can be defined as the duplicate and used as a different way in the same area(method).

I maybe guess this pattern can be treated well.

Good Luck!

**Comment by JustGregory** [comment]
Just my two cents:
For reference, local (in-method) conflicts might be handled differently in other decompilers, and in different scenarios. We could also look at how @MinecraftForge uses a fernflower decomp process; with Minecraft Forge, I know that to deobfuscate classes, it decompiles to "intermediate" sources, resulting in a lot of "field_*", "func_*", and even parameter named entries, to which an additional step translates to human-readable field, method, and parameter names. I rather like it (except for each Minecraft Forge release I'm still dealing with leftover holdout "func_" methods who don't get a rename...).

For what @exatoa ends up saying, local variable conflicts could be handled in a similar process. It may add a new layer to the decompilation (a little more use of a temp directory and generating something like Forge's SRG renaming indices for each project) but I personally would have no problem in that regard.

Additionally, I'm not sure either Minecraft Forge or fernflower does any optimizations such as for iteration (list-size/integer-index) translation to a "for each" structure, but, sorry to say @exatoa I personally rather prefer to do such "optimization" myself, in my IDE.

**Comment by emmanue1** [comment]
Fixed
