### ISSUE TITLE
run in 2016MacBook Pro crash

### ISSUE THREAD

**Issue by Suma-sun** [java-decompiler/jd-gui#157]
Process:               jd-gui [1901]
Path:                  /Volumes/VOLUME/*/JD-GUI.app/Contents/MacOS/jd-gui
Identifier:            jd.jd-gui
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           jd-gui [1901]
User ID:               501

Date/Time:             2016-11-27 22:50:41.381 +0800
OS Version:            Mac OS X 10.12.1 (16B2659)
Report Version:        12
Anonymous UUID:        482676A9-EE3A-AEF6-01F4-EA8F21987798

Sleep/Wake UUID:       CF5CA241-C60E-446D-B993-865DD3B1707C

Time Awake Since Boot: 8800 seconds
Time Since Wake:       8100 seconds

System Integrity Protection: disabled

Crashed Thread:        Unknown

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000241499f5
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x248b8b5b  ebx: 0xbffffc14  ecx: 0x241499f5  edx: 0x00000001
  edi: 0xbffffc48  esi: 0x00000000  ebp: 0xbffffbd8  esp: 0xbffffb90
   ss: 0x00000023  efl: 0x00010297  eip: 0x000011bb   cs: 0x0000001b
   ds: 0x00000023   es: 0x00000023   fs: 0x00000000   gs: 0x0000000f
  cr2: 0x241499f5
  
Logical CPU:     2
Error Code:      0x00000004
Trap Number:     14

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 7824
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro13,3, BootROM MBP133.0226.B00, 4 processors, Intel Core i7, 2.6 GHz, 16 GB, SMC 2.38f5
Graphics: kHW_IntelHDGraphics530Item, Intel HD Graphics 530, Built-In
Graphics: kHW_AMDRadeonPro450Item, AMD Radeon Pro 450, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x15A), Broadcom BCM43xx 1.0 (7.21.171.47.1a8)
Bluetooth: Version 5.0.1f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: [VIP] JP - Tokyo 185-Nydus-IPSec, IPSec, utun1
USB Device: USB 3.0 Bus
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 11.9
Thunderbolt Bus: MacBook Pro, Apple Inc., 11.9

**Comment by samrocketman** [comment]
Please close this and search for previous issues before opening new ones.  This duplicates #147.
