### ISSUE TITLE
[feature-request] CLI for saving all sources

### ISSUE THREAD

**Issue by Lekensteyn** [java-decompiler/jd-gui#16]
First of all, thank you for your work on jd-gui!

My primary use case of jd-gui is decompilation of Android jar files to readable source code for auditing purposes. The *Save All Sources* option is already a gem, but it is quite repetive work.

Would it be possible to add a CLI entry point/option for this option?

Proposed options:

 - `-z some-src.zip`: writes the sources for given jar(s?) to some-src.zip
 - `-d dir`: writes the sources for given jar(s?) into a directory.

Some other projects that wraps around a jd interface (linked from [Stackoverflow](http://stackoverflow.com/q/1384619/427545)):
 - https://github.com/nviennot/jd-core-java
 - https://github.com/kwart/jd-cmd

**Comment by fdeandao** [comment]
+1
The others projects dont works for you?

**Comment by Lekensteyn** [comment]
I haven't tried those. In the past I also looked into using the other interfaces (eclipse?) to convert sources, but now that the sources are open it should be easier to implement it.

Btw, the current code is tightly coupled with the GUI interfaces, so this requires a bit of effort (I suspended it after a day).

**Comment by TaylorSMarks** [comment]
My problem with those other projects is that it looks like they require you to build them yourself. I want to just get the jar and start running it from the command line.

**Comment by emmanue1** [comment]
Create a simple CLI looks simple, nevertheless, before create a new project, have you try this one?

https://github.com/fesh0r/fernflower
java -jar fernflower.jar [-<option>=<value>]* [<source>]+ <destination>
