### ISSUE TITLE
do i need to install LAUNCH4J myself?

### ISSUE THREAD

**Issue by drogbababa** [java-decompiler/jd-gui#167]
ERROR: 'LAUNCH4J_HOME' not defined or invalid. Launch4j (http://launch4j.sourceforge.net) is required to generare 'jd-gui.exe'.

**Comment by drogbababa** [comment]
problems solved. There are 2 ways to solve it. Both of them required you download launch4j.exe frist.
remember your download path.
solution 1
use command "gradlew build -DLAUNCH4J_HOME=your launch4j downloadpath\launch4j" in IJ's terminal
solution 2
in build.gradle. delete " def launch4jExe = System.properties['LAUNCH4J_HOME'] + '/launch4j.exe'"
                       use "your launch4j downloadpath\launch4j.exe" instead.

**Comment by AgentW4C** [comment]
@drogbababa I think it is enough to read instructions in [README](https://github.com/java-decompiler/jd-gui/blob/master/README.md), section [How to build JD-GUI](https://github.com/java-decompiler/jd-gui#how-to-build-jd-gui-)...

```
> iexplore http://sourceforge.net/projects/launch4j/files/launch4j-3/3.7/launch4j-3.7-win32.zip/download
> unzip launch4j-3.7-win32.zip
> ./gradlew -DLAUNCH4J_HOME=.../path/to/launch4j-3.7-win32 installWindowsDist
```
generate "build/install/jd-gui-windows/jd-gui.exe"

**Comment by emmanue1** [comment]
Current "build.gradle" downloads launch4j from Maven.org. You do not have to do it yourself anymore.
