### ISSUE TITLE
why not support java 8 ?

### ISSUE THREAD

**Issue by hhhaiai** [java-decompiler/jd-gui#177]
why not support java 8 ?

**Comment by cmoine** [comment]
I suggest to integrate http://www.benf.org/other/cfr/ for Java 8 decompilation.

Would you like me to do a Pull Request ?

**Comment by samrocketman** [comment]
@cmoine the maintainer hasn't been active lately.  I think a pull request for Java 8 support is still valuable because those who really need it could build your PR.

**Comment by java-decompiler** [comment]
Hi, a new major version of JD-Core is coming. Main feature : support of
Java 8.

2017-07-20 10:09 GMT+02:00 Sam Gleske <notifications@github.com>:

**Comment by cmoine** [comment]
Ah, then I guess there is no need to integrate a third party library for decompiling Java 8, thanks. Shoudl we close the ticket, or leave it as a reminder to integrate JD-CORE into JD-GUI ?

**Comment by nolddor** [comment]
any updates?

**Comment by java-decompiler** [comment]
![image](https://user-images.githubusercontent.com/11619605/33218993-3dd7d4e8-d140-11e7-8792-632285c2ecdf.png)

**Comment by java-decompiler** [comment]
![image](https://user-images.githubusercontent.com/11619605/33219014-5fd71c48-d140-11e7-9de0-9e209f08154d.png)

**Comment by CSAC1** [comment]
This would be very helpful, considering that jd gui is the best decompiler out there currently.

**Comment by manikantag** [comment]
Any update when the new version might be released?

**Comment by emmanue1** [comment]
New JD-Core 1.0 is coming with Java 8+, lambda, local method class, try-with-resources statement, default method support.

**Comment by CSAC1** [comment]
Does this come with jd gui also? The latest one I downloaded does not seem to support java 8.

**Comment by mrswadge** [comment]
I've not tested yet, but did you try this one?

https://github.com/java-decompiler/jd-gui/releases/tag/v1.4.1

**Comment by CSAC1** [comment]
I tried it as soon as I got the initial notification. It does not work. Shows// INTERNAL ERROR //
on classes with java 8.

**Comment by mrswadge** [comment]
I've tested now. Using release v1.4.1 I'm getting the same from the following line inside our class.

```
return cache.get( name, () -> LOGGER_CACHE_LOADER.load( name ) );
```

When decompiled the result is:

```
// INTERNAL ERROR //
```

**Comment by emmanue1** [comment]
JD-GUI 1.4.1 include the Java 9+ support only : you can launch jd-gui with a JDK 9, 10 or 11 now. But, this release contains the old JD-Core 0.7.1 which does not allow to decompile lambdas.

On http://java-decompiler.github.io, you can download a preview of the new JD-Core which allows to decompile lambdas.
![image](https://user-images.githubusercontent.com/11559196/54723108-c7106a80-4b66-11e9-9971-30eaf2745789.png)

**Comment by samrocketman** [comment]
Welcome back @emmanue1 😄
