### ISSUE TITLE
Classes using Java 8 Stream API cannot be decompiled

### ISSUE THREAD

**Issue by peschmi2000** [java-decompiler/jd-gui#182]
Classes that use the Stream API introduced with Java 8 do not get decompiled. Instead the opened tab contains the message _// INTERNAL ERROR //_. This can be verified with the following simple class:

```java
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class StreamTest {
    public void streamTest() {
        List<String> strings = new ArrayList<>();
        strings = strings.stream().map(t -> t.toLowerCase()).collect(Collectors.toList());
    }
}
```

**Comment by emmanue1** [comment]
JD-GUI 1.4.3 + JD-Core 1.0.0 support Lambda. Download last release.
