### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MPeti1** [java-decompiler/jd-gui#195]
When i try to open JD-GUI it crashes instantly. I use Windows 10 x64 and i tried both the jar and exe versions. i've had it working some time ago, now it just don't want to work.
Here is the crash log:
[hs_err_pid7376.log](https://github.com/java-decompiler/jd-gui/files/1643811/hs_err_pid7376.log)

**Comment by emmanue1** [comment]
You are not the first to report this problem. Could you test the last version (1.4.1) ?

**Comment by emmanue1** [comment]
No response. I close this issue.

**Comment by MPeti1** [comment]
Sorry for not responding, Github notifications go to an email account I not really use and no Github android app is able to send notifications..
If you are interested, it seems the problem is gone, while still using 1.4.0
