### ISSUE TITLE
Save source could insert blank lines to get generated code lines in the correct position in the file

### ISSUE THREAD

**Issue by matthieu-labas** [java-decompiler/jd-gui#2]
When decompiling a class, a comment in front of each code line shows the line in the original source file. It would be great to have the code line at the same line in the generated source.

E.g. in the screenshot, code line `int oTag = ...` is at line `450` in original source but at line `213` in saved source.

![dummy](https://cloud.githubusercontent.com/assets/7780427/6829677/4687b1b6-d315-11e4-972d-4aad9338c6a2.png)

**Comment by emmanue1** [comment]
If you check "Realign line numbers" in "Source Saver" preferences, original line numbers should match with file line numbers.

![preferences](https://cloud.githubusercontent.com/assets/11559196/6831093/7b097e48-d31e-11e4-9203-a9db4db98e32.png) ![source](https://cloud.githubusercontent.com/assets/11559196/6831100/874b53e8-d31e-11e4-9299-f73d596d1233.png)
