### ISSUE TITLE
The vision 1.4.0 for windows is not suitable for high score screen

### ISSUE THREAD

**Issue by qingyun1988** [java-decompiler/jd-gui#203]
The vision 1.4.0 for windows is not suitable for high score screen. Can you change it?

**Comment by emmanue1** [comment]
Sorry to replay so late.

**Comment by emmanue1** [comment]
Sorry to reply so late. Some information about high-DPI display:
- Java 9 adds High-DPI display support
- You can scale JD-GUI with "sun.java2d.uiScale"

Examples:
- java –Dsun.java2d.uiScale=1.5 -jar jd-gui.1.2.3.jar
- jd-gui.exe –Dsun.java2d.uiScale=2.0

**Comment by TheAndrey** [comment]
Will there be a fix for Java 8? The latest versions also support DPI. JavaFX applications work well.
