### ISSUE TITLE
INTERNAL ERROR when opening jdk1.8.0_172\jre\lib\ext\sunjce_provider.jar!\com\sun\crypto\provider\SealedObjectForKeyProtector.class

### ISSUE THREAD

**Issue by wilx** [java-decompiler/jd-gui#207]
I am seeing `INTERNAL ERROR` when opening `jdk1.8.0_172\jre\lib\ext\sunjce_provider.jar!\com\sun\crypto\provider\SealedObjectForKeyProtector.class`. This is specific to 172 and 171 versions of the Java 8 JDK/JRE.

**Comment by emmanue1** [comment]
Fixed with last release.
