### ISSUE TITLE
jd-gui 1.0 static block will be lost on the class and main method can not be decompiled

### ISSUE THREAD

**Issue by fjh658** [java-decompiler/jd-gui#21]
1. this class download url
http://pan.baidu.com/s/1ntssvk1

2. static block will be lost on the class, in the outline of the left is to show static icons
![image](https://cloud.githubusercontent.com/assets/5550316/7664610/787c19f2-fbc2-11e4-86d8-4bfaf30fa2d2.png)

![image](https://cloud.githubusercontent.com/assets/5550316/7664567/9549c568-fbc0-11e4-8701-a6e33a30770b.png)

3.main method can not be decompiled
![image](https://cloud.githubusercontent.com/assets/5550316/7664585/bf9a850e-fbc1-11e4-9d43-cd90b10cd535.png)

**Comment by fjh658** [comment]
jd-gui 0.3.5 Although there is no normal static block decompile, but static block content is there. 1.0 Block contents are not

![image](https://cloud.githubusercontent.com/assets/5550316/7764700/d0bde180-0087-11e5-81b8-526b61db60b7.png)

**Comment by emmanue1** [comment]
You report two different bugs:
1. JD-Core failed to decompile your class. I keep your file for a futur analysis, but it's not the good place to report it.
2. A static block appears in the tree but decompiled source code does not display a such block. Javac creates a synthetic static block in the CLASS files to store instructions needed to initialize fields. JD-Core rebuilds the field initializations. At the end of the process, the static block may be empty, so it is not displayed. JD-GUI do not a such advanced analysis : it just uses ASM to retrieve fields and methods. A fixe has added to JD-GUI : if you click on a treenode of a static block, and if the source does not contain a such bloc, the class name will be highlighted, instead.

**Comment by emmanue1** [comment]
You report two different bugs:
- JD-Core failed to decompile your class. I keep your file for a futur analysis, but it's not the good place to report it.
- A static block appears in the tree but decompiled source code does not display a such block. Javac creates a synthetic static block in the CLASS files to store instructions needed to initialize fields. JD-Core rebuilds the field initializations. At the end of the process, the static block may be empty, so it is not displayed. JD-GUI do not a such advanced analysis : it just uses ASM to retrieve fields and methods. A fixe has added to JD-GUI : if you click on a treenode of a static block, and if the source does not contain a such bloc, the class name will be highlighted, instead.

**Comment by SetoKaiba** [comment]
I encounter similar bug @emmanue1 .
I use the latest 1.4.0 jd-gui. The static initializer block is missing.
The block contains the obfuscated string encryption code. But it is missing in the 1.4.0 jd-gui.

**Comment by SetoKaiba** [comment]
`static {

        final String[] z = new String[2];

        final int n = 0;

        final char[] charArray = "\u001c-\u000042".toCharArray();

        int length;

        int n3;

        final int n2 = n3 = (length = charArray.length);

        int n4 = 0;

        while (true) {

            Label_0096: {

                if (n2 > 1) {

                    break Label_0096;

                }

                length = (n3 = n4);

                do {

                    final char c = charArray[n3];

                    char c2 = '\0';

                    switch (n4 % 5) {

                        case 0: {

                            c2 = '-';

                            break;

                        }

                        case 1: {

                            c2 = '\u001d';

                            break;

                        }

                        case 2: {

                            c2 = '0';

                            break;

                        }

                        case 3: {

                            c2 = '\u0004';

                            break;

                        }

                        default: {

                            c2 = '\u0003';

                            break;

                        }

                    }

                    charArray[length] = (char)(c ^ c2);

                    ++n4;

                } while (n2 == 0);

            }

            if (n2 > n4) {

                continue;

            }

            break;

        }

        z[n] = new String(charArray).intern();

        final int n5 = 1;

        final char[] charArray2 = "I+\u0003a0N+\u0007a5O|Tfg\u001e%Q7;Lx\u000401\u0014$\b3aH.".toCharArray();

        int length2;

        int n7;

        final int n6 = n7 = (length2 = charArray2.length);

        int n8 = 0;

        while (true) {

            Label_0212: {

                if (n6 > 1) {

                    break Label_0212;

                }

                length2 = (n7 = n8);

                do {

                    final char c3 = charArray2[n7];

                    char c4 = '\0';

                    switch (n8 % 5) {

                        case 0: {

                            c4 = '-';

                            break;

                        }

                        case 1: {

                            c4 = '\u001d';

                            break;

                        }

                        case 2: {

                            c4 = '0';

                            break;

                        }

                        case 3: {

                            c4 = '\u0004';

                            break;

                        }

                        default: {

                            c4 = '\u0003';

                            break;

                        }

                    }

                    charArray2[length2] = (char)(c3 ^ c4);

                    ++n8;

                } while (n6 == 0);

            }

            if (n6 <= n8) {

                z[n5] = new String(charArray2).intern();

                c.z = z;

                a = new BigInteger(c.z[1], 16);

                b = new BigInteger(c.z[0], 16);

                return;

            }

            continue;

        }

    }`
Here's the static initializer block for example.
