### ISSUE TITLE
“JD-GUI.app” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by EarthCitizen** [java-decompiler/jd-gui#211]
macOS High Sierra 10.13.6
JD-GUI version: 1.4.0
Double click app icon and get this error dialog:
"“JD-GUI.app” can’t be opened because it is from an unidentified developer."

Is it possible to sign the app so that this error won't happen? I can't do any of the normal work-arounds as this is a locked-down machine.

**Comment by EarthCitizen** [comment]
Does not work on my machine. Can an app be released that is signed? That is the best solution. The only solution that I am aware of when a Mac is locked down.

**Comment by emmanue1** [comment]
What happens if you build JD-GUI yourself on your laptop?
Command: gradlew build

**Comment by emmanue1** [comment]
Have you try ?

**Comment by EarthCitizen** [comment]
@emmanue1 Sorry for the delay. I tried it, and when I build it myself it works! Thanks.

**Comment by emmanue1** [comment]
Nice.
