### ISSUE TITLE
ubuntu 1804 can't launch jd-gui

### ISSUE THREAD

**Issue by leowang22** [java-decompiler/jd-gui#214]
Download jd-gui_1.4.0-0_all.deb on Ubuntu 1804
can't launch jd-gui!!!

**Comment by bprfh** [comment]
Download the .jar and launch it via terminal with the following command:
 java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar /path/to/jar

**Comment by GilmarBernardes** [comment]
I downloaded .jar file(jd-gui-1.4.0.jar) and changed the java version the will open It

1 - Right click on file
2 - Properties
3 - Open With tab
 - So I choose Oracle Java 8 Runtime as default.

My ubuntu version is 18.04.1 LTS

ps.:  tried to run it with OpenJDK Java 8 Runtime and Oracle Java 11 Runtime and doesn't work.

**Comment by manuvs13** [comment]
I'm also u

> I downloaded .jar file(jd-gui-1.4.0.jar) and changed the java version the will open It
> 
> 1 - Right click on file
> 2 - Properties
> 3 - Open With tab
> 
> * So I choose Oracle Java 8 Runtime as default.
> 
> My ubuntu version is 18.04.1 LTS
> 
> ps.: I tried to run it with OpenJDK Java 8 Runtime and Oracle Java 11 Runtime and doesn't work.

I'm also using Ubuntu 18.04. Initially, it was not worked for me. If you right-click and try to open with oracle java 11 it will not work.
(I'm using Java 11.)
![selection_001](https://user-images.githubusercontent.com/15267119/52394473-7837d580-2ad0-11e9-92e9-0a021dec49d9.png)

To make it work, you have to give executable permission for the .jar file
$ chmod -R a+x jd-gui-1.4.0.jar or
$ chmod -R 777 jd-gui-1.4.0.jar

Then go to the file location where the jd-gui-1.4.0.jar is located. In my case, it is in Downloads. and run the following command
$ java --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -jar jd-gui-1.4.0.jar

**Comment by emmanue1** [comment]
Fixed: Groovy libraries updated.
