### ISSUE TITLE
// INTERNAL ERROR //

### ISSUE THREAD

**Issue by Iqra786** [java-decompiler/jd-gui#216]
I can see the files and code when I drop a jar file in jd-gui. When I save all sources and open the files. It shows me only internal errors messages.

**Comment by mrbesen** [comment]
Happens to me too, i guess it happens because i try to decompile a jar that requires other jar-libraries.

**Comment by mrbesen** [comment]
#197

**Comment by emmanue1** [comment]
No information to debug -> Close issue.
