### ISSUE TITLE
could not modify/edit java class files

### ISSUE THREAD

**Issue by kirantpatil** [java-decompiler/jd-gui#22]
Namaste,

I used jd-gui from santoku linux where they pre-packaged it to reverse engineer mobile apps and other forensic purpose.

I tried to open jar contents and tried to modify the class file content and the jd-gui it not allowing me to edit the files.

Is it how jd-gui works or do I need to make any changes in the jd-gui.

Can you please suggest any alternative where I could modify class files and recompile back to apk (android package) files ?

Thanks,
Kiran.

**Comment by emmanue1** [comment]
Hi, JD-GUI is just a viewer. I suppose you need to use dex2jar to retrieve the JAR file; decompile and save the classes you need change; import JAR and JAVA files in your Android Studio; modify; recompile and repackaged all finally. I've never done.

**Comment by emmanue1** [comment]
Apktool looks the right tool.
