### ISSUE TITLE
java.io.FileNotFoundException: E:\Software\jd-gui\build\tmp\spi\META-INF\services\org.jd.gui.spi.PanelFactory

### ISSUE THREAD

**Issue by stuartdd** [java-decompiler/jd-gui#225]
I get this error (see below) when I did ./gradlew clean build. 
If I clone again then build (without the clean) it works fine!
 
When I run it. The GUI opens OK. I can load up a class file but after that every thing locks up.
I had the same issue when I downloaded the pre-built app. I thought a fresh build might fix it.
Class was biuld on Java 8. 

Build file 'E:\Software\jd-gui\build.gradle' line: 94

* What went wrong:
Execution failed for task ':jar'.
> java.io.FileNotFoundException: E:\Software\jd-gui\build\tmp\spi\META-INF\services\org.jd.gui.spi.PanelFactory (The system cannot find the path specified)

Have used this app with much success in the past and it is really usefull. 

Sorry to report an issue 
:-(

**Comment by emmanue1** [comment]
```
> ./gradlew clean 
> ./gradlew build
```
works fine but 
```
> ./gradlew clean build
```
launched your exception. This is fixed. Commits on Apr 7, 2019, c408b63f9ea5af9389f93ae58fa5da1689f94d1b.
