### ISSUE TITLE
Java decompiler compatibility issue

### ISSUE THREAD

**Issue by SapphireSilence** [java-decompiler/jd-gui#226]
I was using Parrot Security and I downloaded the Java Decompiler but when i runned it it just closed.
After some days (I formatted it but the same version of Parrot), I git cloned and built it and it worked but 
the terminal wrote this:

"WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/pp/jd-gui/build/launch4j/lib/jd-gui-1.4.2.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release"

So, it's a great tool for reverse engineering and I think you should try to put it natively in this OS, then those errors may be gone!

![issue](https://user-images.githubusercontent.com/40866498/54093640-b4cd4a00-4378-11e9-9afe-47612eef5477.png)

**Comment by emmanue1** [comment]
I am removing Groovy from the project. Groovy is cool but, jd-gui.jar is huge, JD-GUI is slow to launch and it produces problems with Java 9+.

**Comment by emmanue1** [comment]
Groovy removed. Try JD-GUI 1.4.2.
