### ISSUE TITLE
jd-gui-1.4.1-jd-core-1.0.0-preview-20190315

### ISSUE THREAD

**Issue by Marbaf** [java-decompiler/jd-gui#228]
Hi,
Sorry to open an issue to provide feedback about this new package (glad of this revival).
Just tried to open class org.springframework.boot.loader.ExecutableArchiveLauncher.class (1.4.2.RELEASE) and both JD-Core windows display:
// INTERNAL ERROR //

No issue when opening the same file (with far less handy) Luyten-0.5.4.

Keep the good work

**Comment by emmanue1** [comment]
Thanks for your bug report. Strange, it works on my side:
![image](https://user-images.githubusercontent.com/11559196/54720121-e99e8580-4b5e-11e9-9204-9ae5ef70d1e7.png)
I launch the preview with jdk-8u152-windows-x64. What is your OS name and Java version ?

**Comment by Marbaf** [comment]
Thanks for answering.
I apologize opening official spring-boot-loader jar from https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-loader/1.4.2.RELEASE also works for me (windows10, java 1.8.0_201).
Having then opened my company's jar, just find out that classes from former jar, still loaded, all display INTERNAL ERROR now... It would be a resource limitation then. When opening a class file, the entire tree is loaded (to allow search I presume) and it may take several seconds with our jars containing lots of libs.

I removed libs folder and other stuffs from jar content, and I can see class content from new JD-Core window while old one displays INTERNAL ERROR.
Maybe I should provide more resources to JD-GUI to avoid this outcome (double-click on jar to launch the GUI).

**Comment by emmanue1** [comment]
I've fix a similar bug on JD-Core 1.0.0 : when a inner class was missing, a Exception was thrown. I'll update the JD-Core 1.0.0 preview.

**Comment by emmanue1** [comment]
If you want add more resources to JD-GUI, try that : java -Xmx1g -jar jd-gui-1.4.1.jar
