### ISSUE TITLE
methods sequence not decompiled successfully

### ISSUE THREAD

**Issue by zifeihan** [java-decompiler/jd-gui#229]
hello, the jd-gui decompiled method statement sequence is ko. and  you can try this class file, please rename it to .class with the suffix.

[org.mybatis.spring.SqlSessionTemplate.txt](https://github.com/java-decompiler/jd-gui/files/3029542/org.mybatis.spring.SqlSessionTemplate.txt)

**Comment by emmanue1** [comment]
Thx @zifeihan, I'll take a look.

**Comment by emmanue1** [comment]
Fixed. I'll publish a new preview.
