### ISSUE TITLE
Method Refernce Error

### ISSUE THREAD

**Issue by chdw** [java-decompiler/jd-gui#233]
Open this classes will show // INTERNAL ERROR //
and no method source

[xx.zip](https://github.com/java-decompiler/jd-gui/files/3078658/xx.zip)

**Comment by emmanue1** [comment]
JD-GUI 1.4.1 includes the old JD-Core 0.7.1 which does not allow to decompile lambdas.
On http://java-decompiler.github.io, you can download a preview of the new JD-Core 1.0.0 which allows to decompile lambdas.
