### ISSUE TITLE
Build Failure jd:jd-core:0.7.1

### ISSUE THREAD

**Issue by DesBlock** [java-decompiler/jd-gui#236]
Failure when attempting to build from source on Ubuntu 18. Look like the jd-core directory may have been moved recently (mvn-repo/jd to mvn-repo/org/jd) and the location was not updated to match the current code. (Error below)

![image](https://user-images.githubusercontent.com/7647070/56601237-9b9af880-65c8-11e9-9e93-e09749227c47.png)

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/jdgui/build.gradle' line: 68

* What went wrong:
A problem occurred evaluating root project 'jd-gui'.
> Could not resolve all files for configuration ':app:runtime'.
   > Could not find jd:jd-core:0.7.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/jd/jd-core/0.7.1/jd-core-0.7.1.pom
       - https://repo.maven.apache.org/maven2/jd/jd-core/0.7.1/jd-core-0.7.1.jar
       - https://raw.github.com/java-decompiler/mvn-repo/master/jd/jd-core/0.7.1/jd-core-0.7.1.pom
       - https://raw.github.com/java-decompiler/mvn-repo/master/jd/jd-core/0.7.1/jd-core-0.7.1.jar
     Required by:
         project :app > project :services

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by phartshorn** [comment]
I've just hit this issue as well. I was able to get it to build by editing `services/build.gradle` and change line 6 from `compile 'jd:jd-core:0.7.1'` to `compile 'org.jd:jd-core:0.7.1'`

**Comment by DesBlock** [comment]
Thank you so much, that worked perfectly.

**Comment by pdog18** [comment]
> I've just hit this issue as well. I was able to get it to build by editing `services/build.gradle` and change line 6 from `compile 'jd:jd-core:0.7.1'` to `compile 'org.jd:jd-core:0.7.1'`

It works for me.

**Comment by emmanue1** [comment]
Fixed.
