### ISSUE TITLE
Can not save configuration in 1.4.3, and can not drag a jar file into jd-gui

### ISSUE THREAD

**Issue by zhufeizzz** [java-decompiler/jd-gui#238]
OS：Win10

1. When I save configuration, "jd-gui.cfg" file in "C:\Users\xxx\AppData\Roaming" is empty, configuration can not be saved.
2. I can drag a jar file into jd-gui now

**Comment by emmanue1** [comment]
Have you a stacktrace when you lanch JD-GUI with "java -jar jd-gui-1.4.3.jar" ?
