### ISSUE TITLE
JD-GUI does not start with OpenJDK 11 

### ISSUE THREAD

**Issue by JRSofty** [java-decompiler/jd-gui#239]
I'm using OpenJDK 11 on Windows 10, and JD-GUI refuses to start and provides an alert that says it requires a Java 7 environment.

**Comment by boldforlife** [comment]
I had the same problem.
I think it might work:
Download ```jd-gui-1.4.3.jar```
Command line: ```java -jar .\jd-gui-1.4.3.jar```

**Comment by emmanue1** [comment]
In progress... https://sourceforge.net/p/launch4j/bugs/197/
