### ISSUE TITLE
Add support for obr files

### ISSUE THREAD

**Issue by jonavon** [java-decompiler/jd-gui#24]
OSGi Bundle Repository

**Comment by emmanue1** [comment]
Have you samples files ?

**Comment by jonavon** [comment]
It's most likely not necessary. It seems that Atlassian just names the jar files into .obr files.
https://developer.atlassian.com/docs/atlassian-platform-common-components/plugin-framework/osgi-spring-and-the-plugin-framework#OSGi,SpringandthePluginFramework-OSGiTerminology

**Comment by jonavon** [comment]
You could just enable All filetypes. *.*

**Comment by emmanue1** [comment]
Add ".obr" for JAR files ? Correct ?

**Comment by jonavon** [comment]
correct.
