### ISSUE TITLE
Double Quotes aren't escaped.

### ISSUE THREAD

**Issue by jason8399** [java-decompiler/jd-gui#240]
JD-GUI : 1.4.3
JD-Core: 1.0.0
Compiler: Java 8

Hi, I've found that the double quotes(") in the constant string would not be escaped.

This one is showed and saved by jd-gui:
```java
public class App
{
  public static void main(String[] paramArrayOfString) { 
    System.out.print("<body class="logged-in env-production page-responsive">\n");
  }
}
```
But it should be this one:
```java
public class App
{
  public static void main(String[] paramArrayOfString) { 
    System.out.print("<body class=\"logged-in env-production page-responsive\">\n");
  }
}
```

After tracing code, I suggest that we can add escape function in `LineNumberStringBuilderPrinter` and `ClassFilePrinter` class in jd-gui, or we can add escape function direct to `ConstantStringToken` class in  jd-core.

What do you guys think about this suggestion?

Thanks!

**Comment by emmanue1** [comment]
Thanks. It's fixed : https://github.com/java-decompiler/jd-core/commit/e986b2995b29fcac9ac9d30b0b8b2fc8c893763b
