### ISSUE TITLE
spring boot jar can't decompiler

### ISSUE THREAD

**Issue by ergehenmeng** [java-decompiler/jd-gui#244]
java version "1.8.0_111"
spring boot version 2.0.1
jd-gui 1.5.1
when i package project to jar ,then use jd-gui to decompiler it,all of file 
![微信截图_20190530174451](https://user-images.githubusercontent.com/7636955/58624404-b87ec600-8302-11e9-9365-949e45a02ca7.png)
even if application.properties is blank

**Comment by LemADEC** [comment]
Your java is way outdated, update it to 1.8.0_2xx and try again.

**Comment by emmanue1** [comment]
Fixed. Bug introduced today in JD-Core. @ergehenmeng, thank you for your vigilance.

**Comment by ergehenmeng** [comment]
long time no reply. when i use 1.8.0_2xx,it's right now,i guess spring boot plugin package executable jar,it will add some shell command
