### ISSUE TITLE
Crash on openjdk version 1.8.0_152

### ISSUE THREAD

**Issue by nguyenkien** [java-decompiler/jd-gui#246]
I try to start jd with android studio jre.
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
OpenJDK 64-Bit Server VM (build 25.152-b01, mixed mode)
[hs_err_pid5224.log](https://github.com/java-decompiler/jd-gui/files/3290986/hs_err_pid5224.log)

**Comment by emmanue1** [comment]
Mhhh... do you have a crash with jd-gui-1.5.2.jar or jd-gui-1.6.0.jar too?
have you another JDK ? 9.x for example ?

**Comment by nguyenkien** [comment]
JD-GUI 1.5.2 jar.
No, i only have jdk version come with android studio

**Comment by emmanue1** [comment]
A call to sun.awt.windows.WToolkit.getScreenWidth() will crash your JVM.

**Comment by oliversalzburg** [comment]
I was also using the Android Studio JRE (through `JAVA_HOME`). I changed the environment variable to point to an installation of `jre1.8.0_201` and the application is now working as expected.
