### ISSUE TITLE
String switch statements with fall-through are unhandled

### ISSUE THREAD

**Issue by joankaradimov** [java-decompiler/jd-gui#249]
String switch statements are correctly decompiled to Java code only if they have no fallthroughs in them. In case of a fallthrough only the byte code is displayed.

JD-GUI: 1.6.1

**Comment by emmanue1** [comment]
Could you send a CLASS file ?

**Comment by joankaradimov** [comment]
I think I was wrong about the fallthrough. I was not able to reproduce it the way I thought I could.

I ended up stripping a piece of our production code. I hope it's not too much of a mess:
[MimeTypeDetector.zip](https://github.com/java-decompiler/jd-gui/files/3344998/MimeTypeDetector.zip)

**Comment by emmanue1** [comment]
Java 12 compilator. Ok. Maybe it uses a new control flow. I'll take a look.

**Comment by emmanue1** [comment]
Find. Just a bug again.

**Comment by emmanue1** [comment]
Fixed. See https://github.com/java-decompiler/jd-core/commit/cefe750dbf6012368678836ee847f3c80e423d25
