### ISSUE TITLE
Search function not working correctly

### ISSUE THREAD

**Issue by HispidaBytes** [java-decompiler/jd-gui#250]
On version 1.6.0 the "Java Module" flag was added in the search dialog. When that flag is enabled the search returns 0 results.
It also appears that searching for a string constant is not working correctly when the string in the source code uses the new line character "\n".

Below two GIF showing the problem.

**Version 1.6.0:**
![1_6_0](https://user-images.githubusercontent.com/34475384/60341408-a8641000-99ae-11e9-8a83-4830a3091531.gif)

**Version 1.5.2:**
![1_5_2](https://user-images.githubusercontent.com/34475384/60341410-abf79700-99ae-11e9-8ef4-ea1647777474.gif)

**Comment by emmanue1** [comment]
An NPE was launched when no "module-info.class" had been indexed. It's fixed. Thank you.
