### ISSUE TITLE
The RGB Color code was incorrectly generated 

### ISSUE THREAD

**Issue by Abdumation** [java-decompiler/jd-gui#252]
I am decompiling  a jar file the code is generated fine, but one thing is that the generated color code for the RGB Plate is containing Unicode character instead of the color value. I already Checked "Escape Unicode Character"  option from the preferences but that dose nothing . Generated code  `  UIManager.put("nimbusFocus", new Color(4, 124, 4, '�'));`    Original Code `  UIManager.put("nimbusFocus", new Color(4, 124, 4, 124));`    
I am using the latest version 1.6.2    but it works on the previous version JD-GUI 1.4.2.  Please Fix

**Comment by emmanue1** [comment]
I failed to reproduce the bug. Could you upload a CLASS file ?

**Comment by Abdumation** [comment]
Here is the class file.   
[login.zip](https://github.com/java-decompiler/jd-gui/files/3365363/login.zip)

**Comment by emmanue1** [comment]
Fix : https://github.com/java-decompiler/jd-core/commit/4ca89c92692fb74738814ed8d25c4f7cc429ebee
