### ISSUE TITLE
Crashes on startup on Windows

### ISSUE THREAD

**Issue by oliversalzburg** [java-decompiler/jd-gui#253]
When I start the application, it pretty much instantly crashes after displaying the splash screen for a brief moment.

[hs_err_pid10920.log](https://github.com/java-decompiler/jd-gui/files/3358206/hs_err_pid10920.log)

**Comment by emmanue1** [comment]
Hi @oliversalzburg, you are the second user to report this crash (#246).
Your JVM crash whem `sun.awt.windows.WToolkit.getScreenWidth()` is called.
@nguyenkien uses the same Java version (build 1.8.0_152-release-1343-b01) as you.
This release have a problem.
