### ISSUE TITLE
Can't pin JD-GUI in Windows' taskbar

### ISSUE THREAD

**Issue by maxxyme** [java-decompiler/jd-gui#255]
Currently on Windows 10 Pro (64-bit)

I can't pin JD-GUI in Windows' taskbar.
Only action possible in the contextual menu (right-click) is "Close the window".

While at the same time, using another standard application like e.g. 7-zip File Manager, you have at least 3 entries:
* 7-zip File Manager (which launches a new instance of 7-zip)
* Pin to taskbar
* Close the window

**Comment by mmatela** [comment]
You can pin to taskbar if you run JD-GUI with a shortcut. The shortcut target should be something like `"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\javaw.exe" -jar C:\Software\java-decompiler\jd-gui-1.6.3.jar`

You can also put this shortcut in `%AppData%\Microsoft\Windows\Start Menu\Programs` to add JD-GUI to the start menu.

**Comment by emmanue1** [comment]
Thanks @mmatela, I close this issue.

**Comment by maxxyme** [comment]
OK will check that.

Just surprised, what is the exact explanation then?
