### ISSUE TITLE
Crash on startUp on Win10

### ISSUE THREAD

**Issue by jacklydoudou** [java-decompiler/jd-gui#259]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9d7067837, pid=11460, tid=0x0000000000003b2c
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b01) (build 1.8.0_152-release-1343-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b01 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [awt.dll+0x27837]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00000000036fc800):  JavaThread "main" [_thread_in_native, id=15148, stack(0x0000000003800000,0x0000000003900000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x000000000000000c

Registers:
RAX=0x0000000000000000, RBX=0x0000000000000000, RCX=0x0000000000000000, RDX=0x0000000000000000
RSP=0x00000000038ff488, RBP=0x00000000038ff538, RSI=0x000000001ced5128, RDI=0x0000000000000780
R8 =0x0000000000000001, R9 =0x0000000000000060, R10=0x0000000000000438, R11=0x0000000000000060
R12=0x0000000000000000, R13=0x000000001ced1fe8, R14=0x00000000038ff558, R15=0x00000000036fc800
RIP=0x00007ff9d7067837, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x00000000038ff488)
0x00000000038ff488:   00007ff9d710ce79 00007ff9d7186a18
0x00000000038ff498:   000000001ced1fe8 000000001ced1fe8
0x00000000038ff4a8:   00000000036fc800 fffffffffffffffe
0x00000000038ff4b8:   000000001ced5128 0000000003a97e20
0x00000000038ff4c8:   0000000003aa89a7 000000001ced1fe8
0x00000000038ff4d8:   000000001ced1fe8 0000000000000000
0x00000000038ff4e8:   00000000036fc800 0000000003aa86a2
0x00000000038ff4f8:   00000000038ff4f8 000000001ced1fe8
0x00000000038ff508:   00000000038ff558 000000001cee3b30
0x00000000038ff518:   0000000000000000 000000001ced1fe8
0x00000000038ff528:   0000000000000000 00000000038ff558
0x00000000038ff538:   00000000038ff5b0 0000000003a97ae0
0x00000000038ff548:   0000000000000000 0000000003aa1f16
0x00000000038ff558:   000000076b6a8780 000000076b6b1fb0
0x00000000038ff568:   000000076b6b1fb0 00000000038ff570
0x00000000038ff578:   000000001cedc7dd 00000000038ff5c0 

Instructions: (pc=0x00007ff9d7067837)
0x00007ff9d7067817:   52 10 48 8b c3 48 8b 5c 24 48 48 83 c4 30 5f c3
0x00007ff9d7067827:   cc cc cc cc cc cc cc cc cc 48 8b c1 85 d2 78 05
0x00007ff9d7067837:   3b 51 0c 7c 0a 45 85 c0 75 03 33 c0 c3 33 d2 48
0x00007ff9d7067847:   8b 00 48 63 ca 48 8b 04 c8 c3 cc cc cc cc cc cc 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x0000000000000000 is an unknown value
RCX=0x0000000000000000 is an unknown value
RDX=0x0000000000000000 is an unknown value
RSP=0x00000000038ff488 is pointing into the stack for thread: 0x00000000036fc800
RBP=0x00000000038ff538 is pointing into the stack for thread: 0x00000000036fc800
RSI=0x000000001ced5128 is pointing into metadata
RDI=0x0000000000000780 is an unknown value
R8 =0x0000000000000001 is an unknown value
R9 =0x0000000000000060 is an unknown value
R10=0x0000000000000438 is an unknown value
R11=0x0000000000000060 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x000000001ced1ff0} 'getScreenWidth' '()I' in 'sun/awt/windows/WToolkit'
R14=0x00000000038ff558 is pointing into the stack for thread: 0x00000000036fc800
R15=0x00000000036fc800 is a thread

Stack: [0x0000000003800000,0x0000000003900000],  sp=0x00000000038ff488,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [awt.dll+0x27837]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.awt.windows.WToolkit.getScreenWidth()I+0
j  sun.awt.SunToolkit.getScreenSize()Ljava/awt/Dimension;+5
j  org.jd.gui.service.a.c.a()Lorg/jd/gui/b/a/a;+3
j  org.jd.gui.App.main([Ljava/lang/String;)V+65
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x0000000020bdb000 JavaThread "AWT-Windows" daemon [_thread_in_native, id=13792, stack(0x00000000214d0000,0x00000000215d0000)]
  0x0000000020bd8000 JavaThread "AWT-Shutdown" [_thread_blocked, id=8168, stack(0x00000000213d0000,0x00000000214d0000)]
  0x0000000020bd6800 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=7900, stack(0x00000000212d0000,0x00000000213d0000)]
  0x000000001f373800 JavaThread "Service Thread" daemon [_thread_blocked, id=7044, stack(0x00000000208d0000,0x00000000209d0000)]
  0x000000001f2ed000 JavaThread "C1 CompilerThread3" daemon [_thread_blocked, id=12220, stack(0x00000000207d0000,0x00000000208d0000)]
  0x000000001d53e800 JavaThread "C2 CompilerThread2" daemon [_thread_blocked, id=9940, stack(0x00000000206d0000,0x00000000207d0000)]
  0x000000001f2e8800 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=17380, stack(0x00000000205d0000,0x00000000206d0000)]
  0x000000001f2e3800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=17956, stack(0x00000000204d0000,0x00000000205d0000)]
  0x000000001f28f800 JavaThread "Attach Listener" daemon [_thread_blocked, id=14512, stack(0x00000000203d0000,0x00000000204d0000)]
  0x000000001f28e800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=8768, stack(0x00000000202d0000,0x00000000203d0000)]
  0x000000001d52a000 JavaThread "Finalizer" daemon [_thread_blocked, id=10792, stack(0x00000000201d0000,0x00000000202d0000)]
  0x000000001d522800 JavaThread "Reference Handler" daemon [_thread_blocked, id=14944, stack(0x00000000200d0000,0x00000000201d0000)]
=>0x00000000036fc800 JavaThread "main" [_thread_in_native, id=15148, stack(0x0000000003800000,0x0000000003900000)]

Other Threads:
  0x000000001d51a000 VMThread [stack: 0x000000001ffd0000,0x00000000200d0000] [id=14588]
  0x000000001f374000 WatcherThread [stack: 0x00000000209d0000,0x0000000020ad0000] [id=16932]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 76288K, used 5243K [0x000000076b300000, 0x0000000770800000, 0x00000007c0000000)
  eden space 65536K, 8% used [0x000000076b300000,0x000000076b81edd0,0x000000076f300000)
  from space 10752K, 0% used [0x000000076fd80000,0x000000076fd80000,0x0000000770800000)
  to   space 10752K, 0% used [0x000000076f300000,0x000000076f300000,0x000000076fd80000)
 ParOldGen       total 175104K, used 0K [0x00000006c1800000, 0x00000006cc300000, 0x000000076b300000)
  object space 175104K, 0% used [0x00000006c1800000,0x00000006c1800000,0x00000006cc300000)
 Metaspace       used 5368K, capacity 5538K, committed 5760K, reserved 1056768K
  class space    used 577K, capacity 635K, committed 640K, reserved 1048576K

Card table byte_map: [0x0000000012e50000,0x0000000013650000] byte_map_base: 0x000000000f844000

Marking Bits: (ParMarkBitMap*) 0x0000000069c15aa0
 Begin Bits: [0x00000000142a0000, 0x0000000018240000)
 End Bits:   [0x0000000018240000, 0x000000001c1e0000)

Polling page: 0x0000000001450000

CodeCache: size=245760Kb used=1490Kb max_used=1490Kb free=244269Kb
 bounds [0x0000000003a90000, 0x0000000003d00000, 0x0000000012a90000]
 total_blobs=544 nmethods=220 adapters=238
 compilation: enabled

Compilation events (10 events):
Event: 0.145 Thread 0x000000001f2ed000  215       3       jdk.internal.org.objectweb.asm.ByteVector::enlarge (51 bytes)
Event: 0.145 Thread 0x000000001f2ed000 nmethod 215 0x0000000003c027d0 code [0x0000000003c02940, 0x0000000003c02c68]
Event: 0.146 Thread 0x000000001f2ed000  216       3       java.lang.invoke.MemberName::getReferenceKind (12 bytes)
Event: 0.146 Thread 0x000000001f2ed000 nmethod 216 0x0000000003c02d50 code [0x0000000003c02ea0, 0x0000000003c03010]
Event: 0.146 Thread 0x000000001f2ed000  218       3       java.lang.invoke.MethodType$ConcurrentWeakInternSet::get (54 bytes)
Event: 0.147 Thread 0x000000001f2ed000 nmethod 218 0x0000000003c03090 code [0x0000000003c032c0, 0x0000000003c03f98]
Event: 0.147 Thread 0x000000001f2ed000  217       1       java.lang.invoke.MethodTypeForm::basicType (5 bytes)
Event: 0.147 Thread 0x000000001f2ed000 nmethod 217 0x0000000003c04550 code [0x0000000003c046a0, 0x0000000003c047b0]
Event: 0.151 Thread 0x000000001f2ed000  220       3       jdk.internal.org.objectweb.asm.ClassWriter::put122 (15 bytes)
Event: 0.151 Thread 0x000000001f2ed000 nmethod 220 0x0000000003c04990 code [0x0000000003c04b00, 0x0000000003c04cf8]

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Classes redefined (0 events):
No events

Internal exceptions (10 events):
Event: 0.031 Thread 0x00000000036fc800 Exception <a 'java/lang/NoSuchMethodError': Method sun.misc.Unsafe.prefetchRead(Ljava/lang/Object;J)V name or signature does not match> (0x000000076b307f90) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jni.cpp, line 4011]
Event: 0.090 Thread 0x00000000036fc800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b3f1e08) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.090 Thread 0x00000000036fc800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b3f2018) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.090 Thread 0x00000000036fc800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b3f5030) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.090 Thread 0x00000000036fc800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b3f5240) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.090 Thread 0x00000000036fc800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b3f6380) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.091 Thread 0x00000000036fc800 Exception <a 'java/security/PrivilegedActionException'> (0x000000076b3f6590) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jvm.cpp, line 1390]
Event: 0.094 Thread 0x00000000036fc800 Exception <a 'java/io/FileNotFoundException'> (0x000000076b3fc328) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\jni.cpp, line 709]
Event: 0.118 Thread 0x00000000036fc800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x000000076b610f18) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\methodHandles.cpp, line 1167]
Event: 0.119 Thread 0x00000000036fc800 Exception <a 'java/lang/NoSuchFieldError': method resolution failed> (0x000000076b61e5c0) thrown at [D:\src\AOSP-openjdk-cygwin\jdk8u\hotspot\src\share\vm\prims\methodHandles.cpp, line 1167]

Events (10 events):
Event: 0.151 loading class java/lang/ApplicationShutdownHooks$1
Event: 0.151 loading class java/lang/ApplicationShutdownHooks$1 done
Event: 0.151 loading class java/lang/Shutdown
Event: 0.151 loading class java/lang/Shutdown done
Event: 0.151 loading class java/lang/Shutdown$Lock
Event: 0.152 loading class java/lang/Shutdown$Lock done
Event: 0.152 loading class java/awt/Dimension
Event: 0.152 loading class java/awt/geom/Dimension2D
Event: 0.152 loading class java/awt/geom/Dimension2D done
Event: 0.152 loading class java/awt/Dimension done

Dynamic libraries:
0x00007ff782ac0000 - 0x00007ff782af1000 	C:\Program Files\Java\jre\bin\javaw.exe
0x00007ffa1d300000 - 0x00007ffa1d4ed000 	C:\Windows\SYSTEM32\ntdll.dll
0x00007ffa1c930000 - 0x00007ffa1c9e3000 	C:\Windows\System32\KERNEL32.DLL
0x00007ffa195f0000 - 0x00007ffa19883000 	C:\Windows\System32\KERNELBASE.dll
0x00007ffa1cda0000 - 0x00007ffa1ce43000 	C:\Windows\System32\ADVAPI32.dll
0x00007ffa1c460000 - 0x00007ffa1c4fe000 	C:\Windows\System32\msvcrt.dll
0x00007ffa1c200000 - 0x00007ffa1c29e000 	C:\Windows\System32\sechost.dll
0x00007ffa1c800000 - 0x00007ffa1c922000 	C:\Windows\System32\RPCRT4.dll
0x00007ffa1bf70000 - 0x00007ffa1c107000 	C:\Windows\System32\USER32.dll
0x00007ffa19dc0000 - 0x00007ffa19de0000 	C:\Windows\System32\win32u.dll
0x00007ffa1bb00000 - 0x00007ffa1bb29000 	C:\Windows\System32\GDI32.dll
0x00007ffa19c20000 - 0x00007ffa19db9000 	C:\Windows\System32\gdi32full.dll
0x00007ffa19450000 - 0x00007ffa194f0000 	C:\Windows\System32\msvcp_win.dll
0x00007ffa194f0000 - 0x00007ffa195ea000 	C:\Windows\System32\ucrtbase.dll
0x00007ffa08ad0000 - 0x00007ffa08d49000 	C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17763.615_none_05b4414a072024d4\COMCTL32.dll
0x00007ffa1c9f0000 - 0x00007ffa1cd1c000 	C:\Windows\System32\combase.dll
0x00007ffa19a90000 - 0x00007ffa19b0e000 	C:\Windows\System32\bcryptPrimitives.dll
0x00007ffa1bb30000 - 0x00007ffa1bb5e000 	C:\Windows\System32\IMM32.DLL
0x0000000069ca0000 - 0x0000000069d72000 	C:\Program Files\Java\jre\jre\bin\msvcr100.dll
0x0000000069450000 - 0x0000000069c91000 	C:\Program Files\Java\jre\jre\bin\server\jvm.dll
0x00007ffa1a530000 - 0x00007ffa1a538000 	C:\Windows\System32\PSAPI.DLL
0x00007ffa0fc50000 - 0x00007ffa0fc59000 	C:\Windows\SYSTEM32\WSOCK32.dll
0x00007ffa17ef0000 - 0x00007ffa17efa000 	C:\Windows\SYSTEM32\VERSION.dll
0x00007ffa17000000 - 0x00007ffa17024000 	C:\Windows\SYSTEM32\WINMM.dll
0x00007ffa1c500000 - 0x00007ffa1c56d000 	C:\Windows\System32\WS2_32.dll
0x00007ffa16f90000 - 0x00007ffa16fbd000 	C:\Windows\SYSTEM32\WINMMBASE.dll
0x00007ffa19400000 - 0x00007ffa1944a000 	C:\Windows\System32\cfgmgr32.dll
0x00007ff9f9630000 - 0x00007ff9f966a000 	C:\Program Files\Java\jre\jre\bin\splashscreen.dll
0x00007ffa17500000 - 0x00007ffa1759c000 	C:\Windows\system32\uxtheme.dll
0x00007ffa17f10000 - 0x00007ffa17f1f000 	C:\Program Files\Java\jre\jre\bin\verify.dll
0x00007ff9f95a0000 - 0x00007ff9f95c9000 	C:\Program Files\Java\jre\jre\bin\java.dll
0x00007ffa1c580000 - 0x00007ffa1c6eb000 	C:\Windows\System32\MSCTF.dll
0x00007ffa1bd10000 - 0x00007ffa1bdd4000 	C:\Windows\System32\OLEAUT32.dll
0x00007ffa193b0000 - 0x00007ffa193c1000 	C:\Windows\System32\kernel.appcore.dll
0x00007ffa00af0000 - 0x00007ffa00b06000 	C:\Program Files\Java\jre\jre\bin\zip.dll
0x00007ffa0f410000 - 0x00007ffa0f4a5000 	C:\Windows\System32\TextInputFramework.dll
0x00007ffa14e20000 - 0x00007ffa15142000 	C:\Windows\System32\CoreUIComponents.dll
0x00007ffa16b30000 - 0x00007ffa16c12000 	C:\Windows\System32\CoreMessaging.dll
0x00007ffa1ba50000 - 0x00007ffa1baf8000 	C:\Windows\System32\SHCORE.dll
0x00007ffa18510000 - 0x00007ffa18541000 	C:\Windows\SYSTEM32\ntmarta.dll
0x00007ffa14c90000 - 0x00007ffa14de3000 	C:\Windows\SYSTEM32\wintypes.dll
0x00007ffa177e0000 - 0x00007ffa1780e000 	C:\Windows\system32\dwmapi.dll
0x00007ffa198b0000 - 0x00007ffa19a8b000 	C:\Windows\System32\CRYPT32.dll
0x00007ffa19300000 - 0x00007ffa19312000 	C:\Windows\System32\MSASN1.dll
0x00007ffa19890000 - 0x00007ffa198a7000 	C:\Windows\System32\CRYPTSP.dll
0x00007ffa1a560000 - 0x00007ffa1ba50000 	C:\Windows\System32\SHELL32.dll
0x00007ffa19de0000 - 0x00007ffa1a52a000 	C:\Windows\System32\windows.storage.dll
0x00007ffa19320000 - 0x00007ffa19344000 	C:\Windows\System32\profapi.dll
0x00007ffa19350000 - 0x00007ffa193ad000 	C:\Windows\System32\powrprof.dll
0x00007ffa1c400000 - 0x00007ffa1c452000 	C:\Windows\System32\shlwapi.dll
0x00007ff9d7040000 - 0x00007ff9d71d8000 	C:\Program Files\Java\jre\jre\bin\awt.dll
0x00007ffa163a0000 - 0x00007ffa1695e000 	C:\Windows\SYSTEM32\d2d1.dll
0x00007ffa17270000 - 0x00007ffa172fc000 	C:\Windows\SYSTEM32\apphelp.dll
0x00007ffa1c2a0000 - 0x00007ffa1c3f5000 	C:\Windows\System32\ole32.dll
0x00007ffa091b0000 - 0x00007ffa0939d000 	C:\Windows\SYSTEM32\dbghelp.dll

VM Arguments:
java_command: C:\Users\Administrator\Downloads\jd-gui-windows-1.6.3\jd-gui-windows-1.6.3\jd-gui.exe
java_class_path (initial): C:\Users\Administrator\Downloads\jd-gui-windows-1.6.3\jd-gui-windows-1.6.3\jd-gui.exe
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=C:\Program Files\Java\jre
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\PuTTY\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools;C:\Python27;C:\Python27\Scripts;C:\wget;C:\Program Files\Java\jdk-12.0.1\bin;D:\AOSP\aosp\.repo\repo;C:\MinGW\bin;C:\Users\Administrator\.gradle\wrapper\dists\gradle-5.1.1-all\97z1ksx6lirer3kbvdnh7jtjg\gradle-5.1.1\bin;C:\Users\Administrator\Desktop\windowCmd;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3\bin;;C:\groovy-2.5.7\bin;C:\Program Files\Java\jre\bin;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Java\jre\bin
USERNAME=Administrator
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 17763 (10.0.17763.475)

CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 158 stepping 9, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, rtm, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 16674000k(3838452k free), swap 23489744k(7219228k free)

vm_info: OpenJDK 64-Bit Server VM (25.152-b01) for windows-amd64 JRE (1.8.0_152-release-1343-b01), built by "builder" with MS VC++ 10.0 (VS2010)

time: Thu Aug 01 13:57:32 2019
elapsed time: 0 seconds (0d 0h 0m 0s)

**Comment by emmanue1** [comment]
Hello, you are the third to report this bug : #246, #253.
Your JVM crash whem sun.awt.windows.WToolkit.getScreenWidth() is called.
JDK build 1.8.0_152-release-1343-b01 have a problem.
Update or change your JDK.
