### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by alxchk** [java-decompiler/jd-gui#26]
Please, make fonts configurable. Defaults are horrible..

**Comment by emmanue1** [comment]
To change default UI font, open "jd-gui.cfg" and change "configuration/gui/lookAndFeel".
To change fonts in viewers, edit "rsyntaxtextarea/themes/eclipse.xml" in "jd-gui.jar" and uncomment "baseFont".

**Comment by liubobuzhidao** [comment]
how to change the fontsize of JD-GUI in MacOS?

**Comment by Amunratis** [comment]
Will it work for the fonts of the IDE itself (not just the code)? Moreover, I couldn't find the said .cfg file in my windows install, should I download the source for it?

**Comment by Hritik14** [comment]
@emmanue1  Cannot seem to find the cfg file on my linux install. The default fonts are really a pain to look at. Please elaborate.

**Comment by MalayP98** [comment]
Whenever I am running jd-gui using the jar it create a file by name jd-gui.cfg, how to change the location of creation of this file. Is there something I can change in Info.plist file.
