### ISSUE TITLE
Showing other text file types

### ISSUE THREAD

**Issue by Xfel** [java-decompiler/jd-gui#28]
I'm currently using JD to analyze a jar file that has some text files with unsupported extensions in it. For example, a file ending on .json can't be displayed in jd. Of course, I could just add a new TreeNodeFactory for this and create a pullreq. However, there are actually a lot of these custom files, and adding a special case for all of them is quite tedious. But just allowing to open any file with a plain text viewer might cause serious issues. So I'd suggest to implement a config option which allows to specify a list of extensions which can be opened with the text file viewer.

**Comment by emmanue1** [comment]
I added the loading of an external configuration file, that will be aggregated to the hard coded configuration of each provider. For example, to associate the extensions "json" and "yaml" to TextFileTreeNodeFactoryProvider, add in the same package (in jd-gui-x.y.z.jar) the following file:

TextFileTreeNodeFactoryProvider.properties:
```
selectors=*:file:*.json,*:file:*.yaml
```
TextFileTreeNodeFactoryProvider will be associated with *.txt, *.md, *.SF, *.policy AND *.json, *.yaml

**Comment by CoolV1994** [comment]
May I also suggest adding .xml and .yml extensions?

**Comment by emmanue1** [comment]
Ok for ".yml". ".xml" files are already supported.
