### ISSUE TITLE
Mac version 1.1.0 search cannot display/open files

### ISSUE THREAD

**Issue by skyraintmp** [java-decompiler/jd-gui#29]
7 matches, but no file list displayed
![screen shot 2015-05-26 at 11 05 30 am](https://cloud.githubusercontent.com/assets/248950/7804548/2e6ed7d2-0397-11e5-812e-d1d7b6f62222.png)

Yosemite 10.10.2

**Comment by emmanue1** [comment]
Fixes by "Fixes Java/Groovy dependencies" commit
