### ISSUE TITLE
What am I allowed to do with the Source Code?

### ISSUE THREAD

**Issue by Jacocococo** [java-decompiler/jd-gui#300]
I have read the license, and studied the GNU GENERAL PUBLIC LICENSE Version 3 elsewhere, but something really throws me off.

When I open the App.java file in the source code, at the top, I see this:

/*
 * Copyright (c) 2008-2019 Emmanuel Dupuy.
 * This project is distributed under the GPLv3 license.
 * This is a Copyleft license that gives the user the right to use,
 * copy and modify the code freely for **non-commercial** purposes.
 */

The thing I don't understand is the non-commercial. From what I have understood, there is different versions of the license, but I'm free to use the software for anything.

Non-commercial contradicts that. So what does it mean? Will I not be able to use it, if I get any money at all from it?

**Comment by oxr463** [comment]
> “Free software” does not mean “noncommercial”. A free program must be available for commercial use, commercial development, and commercial distribution. Commercial development of free software is no longer unusual; such free commercial software is very important. You may have paid money to get copies of free software, or you may have obtained copies at no charge. But regardless of how you got your copies, you always have the freedom to copy and change the software, even to sell copies. --[What is free software?](https://www.gnu.org/philosophy/free-sw.en.html)
