### ISSUE TITLE
jd-gui 1.1.0 disabled menu-bar shadow on Windows

### ISSUE THREAD

**Issue by enkunkun** [java-decompiler/jd-gui#31]
It's like disabled "Show shadows under the menu" on visual effects menu

on jd-gui 0.3.6
![jd-gui-0.3.6](https://cloud.githubusercontent.com/assets/1749280/7833880/3e8e36ee-04a5-11e5-8550-7a90fec8a019.png)

on jd-gui 1.1.0
![jd-gui-1.1.0](https://cloud.githubusercontent.com/assets/1749280/7833883/4377819c-04a5-11e5-8edf-3e6864576de4.png)

**Comment by emmanue1** [comment]
I'm not sure that the shadow under the menu bar is the most important feature for a decompiler.
