### ISSUE TITLE
how to use this in java 

### ISSUE THREAD

**Issue by salexus** [java-decompiler/jd-gui#320]
i was trying to make a java program which will take two param. first the input directory and other the destination and create a folder structure same as the input. and convert the class file to java source file in the destination folder.

**Comment by s1099** [comment]
Well, this software does the same thing

**Comment by salexus** [comment]
I want to use this functionality as q part of code so I can make this automated, is there a way for this ?

**Comment by s1099** [comment]
Yes, you need to use the the jd-core backend.
https://github.com/java-decompiler/jd-core

**Comment by salexus** [comment]
Thanks, that was useful.
