### ISSUE TITLE
BigSur ERROR launching 'JD-GUI'

### ISSUE THREAD

**Issue by ly8388** [java-decompiler/jd-gui#332]
ERROR launching 'JD-GUI'

No suitable Java version found on your system!
This program requires Java 1.8+
Make sure you install the required Java version.

java-version 1.8

**Comment by ly8388** [comment]
![image](https://user-images.githubusercontent.com/49558207/99136171-7fedbc00-265e-11eb-86ca-bcf56d425f7e.png)
![image](https://user-images.githubusercontent.com/49558207/99136179-89772400-265e-11eb-86fc-04ebb7764aec.png)

**Comment by ly8388** [comment]
解决了 改了一下sh

**Comment by YuriyPikachu** [comment]
怎么改的啊@ly8388

**Comment by ly8388** [comment]
> 怎么改的啊@ly8388

查看包文件 macos下有个sh启动文件 搜一下JAVA_HOME  把JAVACMD写死。。。

**Comment by skyedai910** [comment]
我这里测试，直接写入 JAVACMD 不生效。将 224-251 行在系统寻找 java 部分注释，然后再写死 JAVA_HOME 后成功启动

**Comment by sixawn** [comment]
大概 250 行，把  	JAVACMD="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java" 写死系统中安装的目录。

**Comment by WizzXu** [comment]
https://blog.csdn.net/csdn_avatar_2019/article/details/110442459?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~aggregatepage~first_rank_v2~rank_v29-4-110442459.pc_aggpage_cache&utm_term=jdgui%E6%89%93%E4%B8%8D%E5%BC%80&spm=1000.2123.3001.4430

**Comment by nuriofernandez** [comment]
I fixed it by putting something like this:
```sh
export JAVA_HOME=$(/usr/libexec/java_home -v11)
```
At the first line of the file:
```
/Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
```

**Comment by markowkes** [comment]
@xXNurioXx Your solution worked for me

**Comment by Remigar2012** [comment]
@xXNurioXx Thanks=)

**Comment by BinLee218** [comment]
找到这个注释 在224行# first check system variable "$JAVA_HOME"
在这个上面export一下Jdk目录就完事了
export JAVA_HOME="/Users/aaaa/jdk/java"

**Comment by boboZeng** [comment]
> 找到这个注释 在224行# first check system variable "$JAVA_HOME"
> 在这个上面export一下Jdk目录就完事了
> export JAVA_HOME="/Users/aaaa/jdk/java"

这个可以   mac的时候** 空格不用加斜杠\ **

**Comment by ngocnd0242** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

@xXNurioXx I tried and working normally. Thank so much!

**Comment by SuvanCheng** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

大爱，真强
💗

**Comment by funkmonster** [comment]
> > I fixed it by putting something like this:
> > ```shell
> > export JAVA_HOME=$(/usr/libexec/java_home -v11)
> > ```
> > 
> > 
> > At the first line of the file:
> > ```
> > /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> > ```
> 
> @xXNurioXx I tried and working normally. Thank so much!

Worked for me too! Fantastic!

**Comment by agitrubard** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

That's absolutely worked!

![Screen Shot 2021-07-11 at 7 01 08 PM](https://user-images.githubusercontent.com/61833677/125202009-5ed77c80-e27a-11eb-8291-caddeab22291.png)

**Comment by ungenius** [comment]
I fixed it by editing JVMVersion which has been set in Info.plist like this
set 1.8+ to 1.8
![image](https://user-images.githubusercontent.com/15306487/129898321-b39d0e77-cacc-469c-ad0d-18bfee01511d.png)

**Comment by windbelike** [comment]
> 找到这个注释 在224行# first check system variable "$JAVA_HOME"
> 在这个上面export一下Jdk目录就完事了
> export JAVA_HOME="/Users/aaaa/jdk/java"

That works!

**Comment by maazmmd** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

This works, use vim or nano editor via command line.

**Comment by emmanue1** [comment]
@xXNurioXx very good work.
@ngocnd0242 @maazmmd @agitrubard I try to fix that this weekend.
Emmanuel.

**Comment by MartinTintin3** [comment]
Someone should make a PR for this

**Comment by kevin-lucifer** [comment]
I think It's cause by the new authority system in macOS, so far, you can modify the Stub.sh like this(from line 220 to line 254)

![image](https://user-images.githubusercontent.com/20728002/139631947-eb5d3fdb-218f-492d-ba57-3f87e8c37428.png)

**Comment by zouchengli** [comment]
> 找到这个注释 在224行# first check system variable "$JAVA_HOME" 在这个上面export一下Jdk目录就完事了 export JAVA_HOME="/Users/aaaa/jdk/java"

这个可以。

**Comment by 21Chance** [comment]
@xXNurioXx thanks

**Comment by alexlm78** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

Thanks a lot, it works for me.

**Comment by qxysg1273** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```
Thanks, it works for me.

**Comment by domicoder** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

Working

**Comment by nikhil2000** [comment]
> > I fixed it by putting something like this:
> > ```shell
> > export JAVA_HOME=$(/usr/libexec/java_home -v11)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > At the first line of the file:
> > ```
> > /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> > ```
> 
> 大爱，真强 💗


it worked,
right click on the application(JD-GUI.app) -> contents ->macos

**Comment by JacksonBailey** [comment]
> Someone should make a PR for this

[Done](https://github.com/JacksonBailey/jd-gui/tree/bigsur-fix). 😎

**Comment by JacksonBailey** [comment]
@ly8388 can you please reopen this? Just because there is a workaround does not mean it is fixed.

**Comment by terwer** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

I think this is the best solution.

**Comment by krnbhargav** [comment]
![https://i.imgur.com/PLILe0j.png](https://i.imgur.com/PLILe0j.png)

not able to fix on my side, i have `macos monterey 12.3.1`.

problem : jd-gui is not opening and no error window also

**Comment by yanoshercohen** [comment]
> ![https://i.imgur.com/PLILe0j.png](https://camo.githubusercontent.com/50303454a61a8e66c5dfae1b4081198ba0f2d8b3616411e3d9dcc14fbc926a13/68747470733a2f2f692e696d6775722e636f6d2f504c494c65306a2e706e67)
> 
> not able to fix on my side, i have `macos monterey 12.3.1`.
> 
> problem : jd-gui is not opening and no error window also

+1
:\

**Comment by terwer** [comment]
> > ![https://i.imgur.com/PLILe0j.png](https://camo.githubusercontent.com/50303454a61a8e66c5dfae1b4081198ba0f2d8b3616411e3d9dcc14fbc926a13/68747470733a2f2f692e696d6775722e636f6d2f504c494c65306a2e706e67)
> > not able to fix on my side, i have `macos monterey 12.3.1`.
> > problem : jd-gui is not opening and no error window also
> 
> +1 :\

I have `macos monterey 12.3.1`,too,but it works.

Do you already install jdk11?

```bash
export JAVA_HOME=$(/usr/libexec/java_home -v11)
```

this script tell jd-jui to use jdk11,if you install jdk8,you can set with another script

check your environment,following is the right result.

```bash
➜  ~ /usr/libexec/java_home -v11 
/Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home
➜  ~ /usr/libexec/java_home -v1.8 
/Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home
➜  ~ /usr/libexec/java_home -v17 
/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
```

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/3259282/163604994-16cb4a5e-662f-436f-88c7-c9845027cc79.png">

**Comment by JacksonBailey** [comment]
@Ryn0K @yanoshercohen try out my [pull request](https://github.com/JacksonBailey/jd-gui/tree/bigsur-fix)! :)

Build with `./gradlew build`. Since it's the gradle wrapper it's super easy to build locally even if you don't have Gradle installed. You just need Java (which you should already have based on the tool haha). In the `build` folder, unzip `jd-gui-osx-1.6.6.zip` to get the `JD-GUI` application.

Please give it a shot and if something doesn't work then comment on my pull request to let me know so we can fix it.

**Comment by RickZhou666** [comment]
@terwer thanks a lot! works for me! 
![image-20220725233936766](https://user-images.githubusercontent.com/49876378/180818889-f2aae25f-0671-4580-aea3-dc92a72f8ed8.png)

**Comment by GitPlayB** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

This is **AMAZING** man!
I've tried adding JAVA_HOME directory and export JAVA_HOME in my .zshrc but it still didn't work, and this finally works. Cheers!

**Comment by jonfuller** [comment]
I found a way to get it launched without editing the startup script.

Launch the app from the terminal, setting `JAVA_HOME` as you're doing it:

```
JAVA_HOME=`/usr/libexec/java_home -F -v 11` open /Applications/JD-GUI.app
```

Hope this helps someone!

**Comment by ShaneCarr** [comment]
> I fixed it by putting something like this:
> 
> ```shell
> export JAVA_HOME=$(/usr/libexec/java_home -v11)
> ```
> 
> At the first line of the file:
> 
> ```
> /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
> ```

I found this helpful. IF it had been in the readme I wonder if that would help others.

**Comment by unionor** [comment]
go to info.plist and remove the + after 1.8 on line 149.
<img width="760" alt="Screenshot 2023-12-12 at 01 43 13" src="https://github.com/java-decompiler/jd-gui/assets/2782474/7885bf0f-9354-4686-bb6f-eaa3579a4bae">

**Comment by devnoname120** [comment]
@unionor's solution works for me. Specifically you need to edit this file:
```
/Applications/JD-GUI.app/Contents/Info.plist
```

**Comment by Boat2017** [comment]
现在是假期。已经收到您的来信，我会尽快回复。

**Comment by StevenJack666** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by usilitel** [comment]
I could not launch JD-GUI.app, but I launched jar-version of JD-GUI (jd-gui-1.6.6.jar) (downloaded from http://java-decompiler.github.io)

**Comment by intellign** [comment]
@unionor works 2024!

**Comment by Boat2017** [comment]
现在是假期。已经收到您的来信，我会尽快回复。

**Comment by StevenJack666** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by abdullahkus** [comment]
After installing Java via Homebrew, I resolved the issue by setting the JAVA_HOME variable as follows:

`export JAVA_HOME=/opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home`

I added this line to the appropriate file (for example, /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh) at the relevant line.

**Comment by jinqinghua** [comment]
jd-gui.sh

export JAVA_HOME=$(/usr/libexec/java_home -v 17)
export PATH=$JAVA_HOME/bin:$PATH
java -jar /Applications/JD-GUI.app/Contents/Resources/Java/jd-gui-1.6.6-min.jar

**Comment by Boat2017** [comment]
现在是假期。已经收到您的来信，我会尽快回复。

**Comment by StevenJack666** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
