### ISSUE TITLE
build failed with latest update1a5b82a03b9f982121fca9a2bc18057fce67fc82 

### ISSUE THREAD

**Issue by Wonfee** [java-decompiler/jd-gui#36]
gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/bin/jd-gui/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating root project 'jd-gui'.
> Plugin with id 'distribution' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.96 secs

**Comment by Wonfee** [comment]
my env:
gradle -v

------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------

Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_79 (Oracle Corporation 24.79-b02)
OS: Linux 3.16.7-ckt5my-very-own-kernel amd64

**Comment by emmanue1** [comment]
The probleme is not the last build, but your environment : by default, "apt-get install gradle" installs an old JDK 1.7.0_79 and an old Gradle 1.4. Download and unzip a recent JDK and Gradle, for exemple JDK 1.8.0_45 and Gradle 2.4.

Setup your environment :
```
export PATH=/home/xxx/Downloads/gradle-2.4/bin:$PATH
export JAVA_HOME=/home/xxx/Downloads/jdk1.8.0_45
```

Check it:
```
------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Linux 3.16.0-30-generic amd64
```
And finally :
```
gradle build
...
BUILD SUCCESSFUL
...
java -jar build/libs/jd-gui-1.1.0.jar
```

**Comment by Wonfee** [comment]
Thank you emmanue1, with your guide I successed !
