### ISSUE TITLE
ERROR launching 'JD-GUI'

### ISSUE THREAD

**Issue by 4332weizi** [java-decompiler/jd-gui#370]
No suitable Java version found on your system!
This program requires Java 1.8+
Make sure you install the required Java version.
<img width="420" alt="WX20210918-172923@2x" src="https://user-images.githubusercontent.com/5563945/133884198-7c706f08-90d4-4f85-91d8-e416d356b9ca.png">
<img width="585" alt="WX20210918-173158@2x" src="https://user-images.githubusercontent.com/5563945/133884250-d0b10c78-64a4-47af-a4a0-ceedc69425e0.png">
<img width="586" alt="WX20210918-173223@2x" src="https://user-images.githubusercontent.com/5563945/133884252-b5a58f10-7a09-4dbe-93ed-a3b5a08f4685.png">

**Comment by rootmout** [comment]
this may help https://github.com/java-decompiler/jd-gui/issues/332

**Comment by 4332weizi** [comment]
Thank you, it works!
