### ISSUE TITLE
can't open on OSX 10.11 DP1

### ISSUE THREAD

**Issue by bunnyblue** [java-decompiler/jd-gui#39]
can't open on OSX 10.11 DP1
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/JD-GUI.app.

**Comment by emmanue1** [comment]
Your issue looks like this one #40. Have you build "JD-GUI" yourself ?

**Comment by bunnyblue** [comment]
no i download from release

**Comment by bunnyblue** [comment]
ok chmod +x /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh
