### ISSUE TITLE
Can't open the jd-gui.app on Mac

### ISSUE THREAD

**Issue by kifile** [java-decompiler/jd-gui#4]
I download the app from here and your website. But both of them can't be opened. The OS reminds me I can't open it. So I have to use the jar.

**Comment by emmanue1** [comment]
JD-GUI.app works fine on Mavrick for me. Which version do you use? Have you an error message if you execute the command "open JD-GUI.app" from the Terminal ?

**Comment by kifile** [comment]
![screenshot 2x](https://cloud.githubusercontent.com/assets/4291864/6866905/afe4ef86-d4b7-11e4-839e-36088862c5b2.png)

Hi, emmanue1. This my screenshot.
My Mac OS version is 10.10.2.

Wish it could help you.

**Comment by emmanue1** [comment]
Have you a JDK 7 or later versions installed on your system ?

**Comment by emmanue1** [comment]
Self-reply: Yes, since you are using the JAR file.
Could you "Show Package Contents", edit "Info.plist", replace "1.6+" with "1.7+" and try to launch application ?

**Comment by kifile** [comment]
Hi, emmanue1, my jdk is 1.8.0_31.

And I have replaced "1.6+" with "1.7+", but still the sample problem.

**Comment by emmanue1** [comment]
Hi kifile, a question again, is this Java application runs your system?
http://buddi.digitalcave.ca/download.jsp

**Comment by kifile** [comment]
It works fine on my system. And I also use some other java based application , all works but this.
