### ISSUE TITLE
Had to make executable universalJavaApplicationStub.sh for OS X

### ISSUE THREAD

**Issue by mrbuk** [java-decompiler/jd-gui#40]
After executing

`gradle installOsxDist`

and moving the JD-GUI.app to `/Applications` I had to addionally execute 

`chmod +x /Applications/JD-GUI.app/Contents/MacOS/universalJavaApplicationStub.sh`

maybe its a good idea to add this to the `README.md`?

**Comment by emmanue1** [comment]
Mmmh, thanks for the feedback. 

Usually, I build JD-GUI.app under Windows and I checks the build under OSX  10.9 and 10.10.

I will add "chmod" command into "build.gradle".

**Comment by emmanue1** [comment]
Fixed by commit 230b44824fbdbfa9368e2c57e24a6834984d8f35
