### ISSUE TITLE
Release Source for Native Version

### ISSUE THREAD

**Issue by md-5** [java-decompiler/jd-gui#44]
Hi Emannuel,

Not sure what inspired you to rewrite jd-gui in Java, but have you considered open sourcing the old 0.3.5 version for posterity?

Thanks

**Comment by emmanue1** [comment]
Hi md-5,

The version, written in Java, doesn't suit you?

JD-Core processes many super-connected structures. With C++, 70% of the development effort was consumed to fix Segmentation Fault errors. Tests (Linux | OSX | Windows) x (32-bits | 64-bits) was very time consuming too. The development of JD was becoming boring.

I'm not sure that opening the C++ code is a good idea : the project was born in 2007.  The source code is the result of 8 years of patches. Before opening it, a refactoring should be done...

Regrads.

**Comment by PuspenduBanerjee** [comment]
Should we really mark it as 'issue'?

**Comment by md-5** [comment]
Release "as is" under some OSS license?

The Java version is nice, but really Java GUIs are horrible (have you seen the Linux file picker for one?). I don't really have any reason to change yet, so the old one is "good enough".

At the very least maybe the GUI could be repurposed.

**Comment by samrocketman** [comment]
Personally, I don't mind the Java GUI.  This project has helped me decompile projects in the past to fix bugs which had no other possible work around.  It being in Java is all the better as I can just execute `java -jar jd-gui.jar` on any platform and it "just works".  Consider me a happy user :smile:.

**Comment by JustGregory** [comment]
Not that my opinion counts for much, but I'm "all in" for the Java development, as I've been using it since before Y2K. I very much appreciate JD-GUI being in Java; and despite the many "security warnings" oft-spoken in security forums, the truth is, a well-managed Java app can be every bit as good as "native" code...
Anyway, my two cents.

**Comment by md-5** [comment]
I'm not against Java at all, it is literally the only language a program in, however I'd still like to see the old version for science.

**Comment by samrocketman** [comment]
Agreed, more open and free software the better.  I fully support releasing the original version should Emmanuel decide to do that.  I pretty much open source everything I write.
