### ISSUE TITLE
jd-gui-1.2.0.jar

### ISSUE THREAD

**Issue by limelect** [java-decompiler/jd-gui#45]
Preference still dose not work. Dose not open

**Comment by emmanue1** [comment]
Have you a stacktrace ?

**Comment by limelect** [comment]
Now that you fixed "Save All" i guess you have the same problem with Preference.

Have you a stacktrace? No 
What is your JVM version?C:\Program Files (x86)\Java\jre1.8.0_20
 What is your architecture? window 7

**Comment by emmanue1** [comment]
Known issue. Take a look here: # 7
