### ISSUE TITLE
The some 'internal error' in this Java decompiler

### ISSUE THREAD

**Issue by kalksdlkdsa** [java-decompiler/jd-gui#452]
I want to decompile some file .jar, but when I open some file .class in this, it show this error:
```
// INTERNAL ERROR //
```
What the error mean?

**Comment by Sinsify** [comment]
I got the same error

**Comment by kalksdlkdsa** [comment]
oofs

**Comment by kalksdlkdsa** [comment]
But some file .class show the code, some show the error

**Comment by kalksdlkdsa** [comment]
I think that is that file .class is incompatible of this Java decompiler or something like that (or the decompiler has some error)

**Comment by kalksdlkdsa** [comment]
Or this is... not compatible with Java or... is the special file

**Comment by kalksdlkdsa** [comment]
I want developer of JD-GUI solving this fast

**Comment by kalksdlkdsa** [comment]
If not, i will see JD-GUI as an outdated Java decompiler

**Comment by kalksdlkdsa** [comment]
I think JD-GUI is outdated, Minecraft (the game that was use to test the decompiler) requires Java 16 (1.17+), but JD-GUI only support to Java 9

**Comment by kalksdlkdsa** [comment]
And I think something that Minecraft is use LWJGL, the library that JD-GUI can't "know" (i think), this is the last comment for this question
