### ISSUE TITLE
JD GUI crash

### ISSUE THREAD

**Issue by Yousha** [java-decompiler/jd-gui#50]
Crash when closing 2-3 openned JAR files.
Windows 7 64-bit Ultimate

Faulting application name: jd-gui.exe, version: 0.0.0.0, time stamp: 0x53ef61f6
Faulting module name: jd-gui.exe, version: 0.0.0.0, time stamp: 0x53ef61f6
Exception code: 0xc0000005
Fault offset: 0x00054c93
Faulting process id: 0x7bc
Faulting application start time: 0x01d0b29c764b5bea
Report Id: cc59fa59-1e8f-11e5-858a-b99843446341

**Comment by emmanue1** [comment]
What happens to you if you redo the same actions with JD-GUI-1.2.0.jar? You have a stacktrace?

**Comment by Yousha** [comment]
I didnt try it...
How to make a Stacktrace of crashes?

**Comment by emmanue1** [comment]
Just try "java -jar jd-gui-1.2.0.jar" under a Command Prompt

**Comment by emmanue1** [comment]
No answer?
