### ISSUE TITLE
"// INTERNAL ERROR //" - glitch

### ISSUE THREAD

**Issue by linuxcodefire** [java-decompiler/jd-gui#53]
When i decompile some jar files i get greeted with // INTERNAL ERROR // like its encoded or encrypted but your jd-gui is suppose to decompile it.

**Comment by emmanue1** [comment]
JD-Core 0.7.1 is built to recognize patterns generated by "javac". If the class, you try to decompile, was generated with ASM or other tools, JD-Core may fail. I close this issue : this is not a GUI bug.

**Comment by linuxcodefire** [comment]
so this cant do any thing to triple obfuscated code?

**Comment by JustGregory** [comment]
I have not heard of "triple obfuscated code", but I do know what obfuscation means. Could you give an example of what that is?

**Comment by spielmap** [comment]
I run into a same issue with 1.4.0 OSX. I tested the same with version 0.3.5 OSX which is doing fine! So this must be a bug in 1.4.0.

**Comment by premek** [comment]
At least the message should be more descriptive

**Comment by optimus29** [comment]
This could be a GUI bug because in the left navigation pane one can see internals of class such as fields and methods.

**Comment by mgurnani** [comment]
Is there a fix for this? I can also see the internals in left nav pane but "Internal Error" on the right side..

**Comment by shahulirshad** [comment]
Any update on why having lambdas causes this?

**Comment by eostermueller** [comment]
This tool got around those problems for me:
https://github.com/deathmarine/Luyten
