### ISSUE TITLE
Can't open file in v1.3

### ISSUE THREAD

**Issue by GeorgeGkas** [java-decompiler/jd-gui#58]
I download the version 1.3 from the website. The deb file and installed it successfully on my Ubuntu machine. When I open the program and click open file nothing happens. No window for file selection is popping up neither the drag-and-drop is working. What have I done wrong?

**Comment by emmanue1** [comment]
Hi. Have you a stacktrace when you launch JD-GUI from a terminal ? Have you updated your JDK? I will re-check on my side.

**Comment by GeorgeGkas** [comment]
what is a stacktrace? And yes I have the last version of jdk.

**Comment by emmanue1** [comment]
Under a terminal, execute :
````
java -jar jd-gui-1.3.0.jar
````
and check if an error appear.

**Comment by GeorgeGkas** [comment]
It's not that your program can't run. I was successful run it with deb package and java, but in both cases when I select FILE OPEN or drag and drop utility, in both cases the file manager can't open.
I work on Uubuntu 15.04 64bit and java 7 both jre and jdk

**Comment by GeorgeGkas** [comment]
Ok I though maybe was a bug in my desktop distro. I work on Unity with gnome shell installed on. I then though that if I go to classic gnome desktop maybe the problem will fixed. And so it did.What a terrible bug anyway. Thanks for the support. You can close the issue!

**Comment by samrocketman** [comment]
Hi @GeorgeGkas, you're not being very clear.  Did you resolve the issue?  If so, how?  If it is truly a bug in jd-gui then the issue should remain open.

**Comment by samrocketman** [comment]
@GeorgeGkas how about typing the following commands in the terminal.

```bash
cat /etc/issue
java -version
```

Copy and paste the output to this issue.  Also, provide a screenshot of your issue.

You also didn't say if the program still didn't work when you run it from the terminal. I mean the following.

```
java -jar jd-gui-1.3.0.jar
```

When the program is running in that mode then try to open files again.  Do you see any funny text in the terminal?  Copy all of it here.

**Comment by GeorgeGkas** [comment]
I'm sorry for my terrible last description. Yes the problem was fixed. It wasn't bug from your program but from my Ubuntu Distro. Sorry for the inconvenienced.

**Comment by samrocketman** [comment]
No worries, you should have the permission to close the issue yourself.
