### ISSUE TITLE
Problem with problematical classes

### ISSUE THREAD

**Issue by theuserbl** [java-decompiler/jd-gui#6]
If you decompiler normal Java-classes, all works ok.
But if you decompile for example the Groovy generated class in your own jar-file in /jd/gui/App.class and scroll the generated source down, then it gives on the command line a lot of erros out (which is not the problem) AND maximizing or resizing the window have no effect for the parts in the window.
In other words: The parts in the window will not be updated. It only updates parts, if you scroll in the Textarea or the Tree.

**Comment by emmanue1** [comment]
I can not reproduce your issue. This always happens for you? What is your JVM version & architecture?

**Comment by theuserbl** [comment]
Oh, with RC3 you have fixed the bug. :)
Now all worlks ok.
