### ISSUE TITLE
Methods not decompiled successfully ( /* Error */ )

### ISSUE THREAD

**Issue by andriman** [java-decompiler/jd-gui#60]
Hello,

I am trying to decompile this file:
https://app.box.com/s/h4lckthkks1c7h0l7dfnti478nlecd5o

Unfortunately, I get **/* Error */**  on methods that I need to "decompile".
Both with **JD-GUI 0.3.6** and **1.0.0**.

**The methods:**
VideoRecMgr.class->**addVideoToMediaStore()**
VideoRecMgr.class->**initializeRecorder()**

Do you have any ideas how to solve it?

**Comment by samrocketman** [comment]
What application is that file from?

**Comment by andriman** [comment]
It's a camera app

**Comment by samrocketman** [comment]
As in name of the app?

**Comment by andriman** [comment]
A camera app extracted from a ROM - not available on android app markets (GPlay, etc..)
Are you pointing towards something or are you just interested in the app? Because it won't run on public ROMs.

**Comment by samrocketman** [comment]
Just curious is all.  I don't plan on downloading the rar file.

**Comment by emmanue1** [comment]
Thanks for this feedback. I keep & close this issue : this is not a GUI bug.
