### ISSUE TITLE
upper and lower case

### ISSUE THREAD

**Issue by vah13** [java-decompiler/jd-gui#63]
Hi
Please, add search by all categories without case sensitive.

**Comment by emmanue1** [comment]
Hi, searches uses the Camel case like Eclipse: "TZ", "timezone", "TimZo" matches TimeZone.

**Comment by vah13** [comment]
I think this is a bad idea (

**Comment by E3V3A** [comment]
Yes, the search function has always been a challenge in jd-gui. So I think I must agree with @vah13 , bad idea. You search for stuff you know. That `TZ` would match `TimeZone` is crazy...

**Comment by samrocketman** [comment]
Correct me if I'm wrong; if "timezone" matches "TimeZone" then isn't the search already case insensitive?  Mind you I've not ever had a need to use search.

**Comment by vah13** [comment]
I think for first step need create not insensitive case search.
if "timezone" = "TimeZone" -> not case insensitive 
if "timezone" != "TimeZone" -> case insensitive

**Comment by samrocketman** [comment]
@vah13 your logic is backwards.  if "timezone" == "TimeZone" -> case insensitive, etc.
