### ISSUE TITLE
Where should I post jd-core issues?

### ISSUE THREAD

**Issue by TehJumpingJawa** [java-decompiler/jd-gui#65]
I'm using jd to decompile a large project, and have come across a fair number of bugs in the source generation logic.

Is there a dedicated git project for jd-core?
If not, do I post such issues here?

**Comment by emmanue1** [comment]
I'm working on a new version that will be published on GitHub.
Today, you can notify a bug by mail only (java.decompiler at gmail.com).
For your project, try these excellent decompilers:
- https://github.com/fesh0r/fernflower
- https://bitbucket.org/mstrobel/procyon
