### ISSUE TITLE
System freeze on launch

### ISSUE THREAD

**Issue by ST-DDT** [java-decompiler/jd-gui#66]
In round about 30-40% the times I start the application the system freezes while showing the splash-screen-cup. The first start per reboot usually work.

Win 7 Prof SP 1 x64 (DE/GER)
Intel i7 Q720 @ 1.60GHz
8GB RAM
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

I could verify the bug with 1.3.0 and 1.4.0, but IIRC it happened with 1.2.0 as well, but i haven't used it for a few months now.
If the system freeze hits me, I cannot move the mouse, press any keys or get any reaction from the computer anymore. Screen does not show any changes, sound loops in ~30s steps => I have to hard reboot/reset the system.

I'm not sure how to reproduce the error as it seems to occur random and especially if I have to use the tool to look something up.
After the splash-screen no more system freezes happen.
I usually have a running eclipse with jd-gui plugin, firefox, thunderbird at that time and sometimes/always? Minecraft, thought I'm not sure whether one of them have anything to do with the freeze. I never had freezes with my computer with any other application before.

I have a strict firewall/system guard policy, but there is nothing in the logs, but I'm not sure whether it could write during the system freeze at all. I cannot/won't shut it down or disable it temporarily. But as it starts at least sometimes without problems I don't know whether this is related at all.

**Comment by samrocketman** [comment]
If a system seemingly freezes at random it's likely you have a hardware issue.  I've seen random freezes occur from processors overheating.  It's also possible that you have bad memory.

You should boot up Linux and run memtest.  If your system doesn't have a temperature sensor for the processor then it would be a good idea to shut it down, pull out the processor, clean off the old high temp silicone, and apply a fresh layer to it.

Regardless I doubt it's a bug in this program.  I've ran jd-gui for a couple years across multiple operating systems and have had no such issue.  I think it's a hardware problem.

**Comment by ST-DDT** [comment]
I will try to run the memtest this weekend, but i doubt, that this is a memory / thermal issue since this is the only application that has every caused them.
I also updated my Java to latest .

Is there a debug option to get some log entries/messages that might help narrowing down the issue?

**Comment by emmanue1** [comment]
As samrocketman said, this sounds like a hardware problem: Java "1.8.0_45" is stable.

About debugging & messages, first, you can execute this command line and check the output messages.
````
java -jar jd-gui-x.y.z.jar
````
Next, if the Java process is frozen but not your system, you can use the JDK tools to generate a thread dump to detect an infinite loop or malfunctions. For example:
````
> cd ...\Java\jdk1.8.0_45\bin
> jps -l
3472 sun.tools.jps.Jps
3948 jd-gui-1.4.0.jar
...
> jstack 3948
Full thread dump Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode):
...
````

**Comment by ST-DDT** [comment]
Oh sorry for not responding anymore.
I can confirm this is not a jd-gui issue as it affect other decompilers as well.
However I was unable to trace the cause. No RAM issues could be found.
IMO its random computer wierdness.

**Comment by samrocketman** [comment]
You could use a jconsole like jvisualvm and debug the decompilers until the freeze.  They all might hang on the same system call which could indicate what hardware is bad.
