### ISSUE TITLE
Search hangs / types left to right instead of right to left

### ISSUE THREAD

**Issue by ralphkurz** [java-decompiler/jd-gui#68]
Hi,

I use the windows exe.
When I open the search and begin to type (in a large jar ~ 800MB, mustn't be a reason), the cursor hangs and the letter appear left to right instead of right to left.

So, I'm unable to search properly.

**Comment by emmanue1** [comment]
800 MB :smile: ? Probably the reason. You have multiple strategies: split your JAR file or increase the JVM memory (-Xmx2048m ...).

**Comment by ralphkurz** [comment]
Yes, with a smaller jar everything is fine.
However, it worked in an older version (0.3.5 ;-) ).
Increasing the JVM memory did not work.

**Comment by samrocketman** [comment]
You could also unzip the jar file first.  Then you just open the individual class files or libraries built-in.
