### ISSUE TITLE
Feature request: Java 8 invokedynamic decompilation

### ISSUE THREAD

**Issue by Szperak** [java-decompiler/jd-gui#71]
Hello,
I know, that every new java version provides some new methods of obfuscation, but java 8 brought something that no decompiler can handle.
Probably, it's that easy as copy-pasting code for invokestatic and adding two null bytes. :smile:

**Comment by emmanue1** [comment]
The legacy JD-Core 0.7.1 cannot compile the InvokeDynamic instructions. I'm working on a new JD-Core. Stay tuned!
