### ISSUE TITLE
can not display source code 

### ISSUE THREAD

**Issue by yuxh** [java-decompiler/jd-gui#72]
when I open a class file with jd-gui 1.4,it display some strange character. I use it in win7 64.
![20150831153631](https://cloud.githubusercontent.com/assets/1754573/9574100/00bd9700-4ff6-11e5-8681-764c28f4703d.png)

**Comment by emmanue1** [comment]
When you launch JD-GUI with a command line (java -jar jd-gui.x.y.z.jar), have you some stacktraces or error messages on the console ? 
It seems that your CLASS file contains a binary file that is not a Java class. A classic scenario is to encrypt CLASS files into a JAR file and decrypt them with a class loader.
The display is ugly. I check it.

**Comment by yuxh** [comment]
sorry,I downloaded jd-gui-windows-1.4.0.zip，it doesn't contain jar file. Should I download something else?

**Comment by samrocketman** [comment]
Yes, download the jar instead.  Then open the program from the cmd prompt.

> ```java -jar jd-gui.x.y.z.jar```

**Comment by yuxh** [comment]
I tried java -jar jd-gui-1.4.0.jar,and it didn't print any tacktraces or error messages.I notice there is another class file named CommMessageGather$1.class in the same directory in which I decompiled CommMessageGather.class  . Maybe it has something to do with it?

**Comment by emmanue1** [comment]
"CommMessageGather$1.class" contains an anonymous Java class. Nothing strange here.

**Comment by yuxh** [comment]
yes,it does the same thing to every class file in my computer.  By the way,I use jdk 1.8.60_x64.

**Comment by emmanue1** [comment]
I fail to reproduce your issue with jd-gui-1.4.0. Have you the same problem with the old jd-gui-0.3.6 ?

**Comment by yuxh** [comment]
yes,it works well. Any differences between the two versions?

**Comment by emmanue1** [comment]
- 0.3.6 => C++ project
- 1.4.0 => Java project

The algorithms are the same, but the two projects share no pieces of code... How to move forward with your issue? Is it possible you send me some CLASS files?

**Comment by TomyJava** [comment]
you need installer "java Decompiler" my Friend. I leave link of different compiler  http://jd.benow.ca/

**Comment by emmanue1** [comment]
2015. Issue closed.
