### ISSUE TITLE
How to decompile 100 Jars?

### ISSUE THREAD

**Issue by fatbird88** [java-decompiler/jd-gui#73]
Hi expert,

How can I decompile 100 Jars simply and save them on my local disk with a zip file like xxx1.src.zip, ... xxx100.src.zip? It is better to save these 100 Jar files in each folder without zip file.
I need a automatic or simplified process for this actions, otherwise I have to do it 100 times

**Comment by emmanue1** [comment]
1. You can add all your JAR files into a single ZIP file, open it with JD-GUI and click on "Save All Sources"
2. You can use a Fernflower (https://github.com/fesh0r/fernflower) for example, and execute this command for each JAR files :

````
java -jar fernflower.jar [-<option>=<value>]* [<source>]+ <destination>
````
