### ISSUE TITLE
Source code is misaligned in case of decompilation errors 

### ISSUE THREAD

**Issue by patric-r** [java-decompiler/jd-gui#74]
Hi,
when using source code alignment and a decompilation error occurs and the error log output in the source is longer than the actual source for the to-be-decompiled method, all following lines are misaligned.

As a quick workaround, a configuration preference like "don't output compilation error details to source code" would help.

**Comment by emmanue1** [comment]
2015. Issue closed.

**Comment by patric-r** [comment]
Hi, has this  issue been fixed in the meanwhile?
