### ISSUE TITLE
Incomplete decompilation

### ISSUE THREAD

**Issue by gsingh93** [java-decompiler/jd-gui#75]
I have a jar file that was generated with dex2jar that I'm trying to view with jd-gui. For one of the class files, only the constructor of the class is shown, but the rest of the class is not. For the other, there was an error when decompiling and the byte code is shown instead.

Two questions:
1. Is submitting just these two class files sufficient for a bug report? Can I email them to you instead? I don't want to post the JAR.
2. I was going to try looking into the issue myself, but I couldn't find where the decompilation happens. Could you point me to the part of the code where this occurs?

**Comment by emmanue1** [comment]
2015. Issue closed.
