### ISSUE TITLE
Could not copy the Unicode character

### ISSUE THREAD

**Issue by 1354092549** [java-decompiler/jd-gui#76]
Could not copy the Unicode character in the code to the clip.(**Use machine translation**)
**Chinese**:无法复制代码中的Unicode字符到剪辑版

**Comment by emmanue1** [comment]
In progress: a pull request send to RSyntaxTextArea team: 
https://github.com/bobbylight/RSyntaxTextArea/pull/147

**Comment by 1354092549** [comment]
Thank you
