### ISSUE TITLE
Synthetic methods are always hidden

### ISSUE THREAD

**Issue by EvelynSubarrow** [java-decompiler/jd-gui#77]
```
.version 52 0
.source Example.java
.class super public Example
.super java/lang/Object


.method synthetic public <init> : ()V
    .limit stack 1
    .limit locals 1
    aload_0
    invokespecial java/lang/Object <init> ()V
    return
.end method

.method synthetic static public main : ([Ljava/lang/String;)V
    .limit stack 2
    .limit locals 1
    getstatic java/lang/System out Ljava/io/PrintStream;
    ldc 'Hello world'
    invokevirtual java/io/PrintStream println (Ljava/lang/String;)V
    return
.end method
```

JD-GUI Output:
```
public class Example {}
```

**Comment by TehJumpingJawa** [comment]
Synthetic methods by definition, do not exist in the original source code - for that reason it seems perfectly reasonable to exclude them from decompiled source.

What's more, there are many instances where synthetic & bridge methods generated by javac MUST NOT be decompiled (as they'll generate invalid source).

That said, there'd be no harm in including them as comments.

**Comment by EvelynSubarrow** [comment]
Synthetic methods meet that definition, but methods with the synthetic bit set have no such constraints.

**Comment by TehJumpingJawa** [comment]
How is the jd decompiler going to know the difference?

Don't forget the java language is a subset of java bytecode; it's quite 
easy to create java bytecode that has no java source equivalent.

Thus the scope of the jd decompiler (or in fact any java decompiler) is 
to decompile the subset of java bytecode that can be generated by a java 
language compiler.

While there's always tolerance of different compilers, and/or 
obfuscators, you can't expect to feed hand-crafted bytecode into a java 
decompiler and receive valid java source out the other end.

**Comment by EvelynSubarrow** [comment]
The decompiler does not need to know the difference. Not giving such an option to the user, however, does not make sense. In the case of CFR and Fernflower, the default is to include such methods, and provide additional information in comments, and Procyon has a switch to enable viewing.

Method properties are not bytecode. I am perfectly aware of various ways a decompiler can be rendered useless through instructions alone, but this is completely irrelevant.

**Comment by emmanue1** [comment]
@TehJumpingJawa, I would not have written a better response.
JD-Core can not display a valid Java source code for the Bridge and Synthetic methods.
The Byte codes could be displayed in comments, but the initial goal of JD-Core was "decompile and realign source code to debug anything".
@EvelynSubarrow, why do you need to see Bridge and Synthetic methods?

**Comment by EvelynSubarrow** [comment]
Marking arbitrary methods as synthetic is used as an obfuscation technique. Having no way to enable viewing allows this.

**Comment by emmanue1** [comment]
Ok for this argument. I will not modify JD-Core 0.7.1, but I keep your suggestion for the new JD-Core 1.0.0. I close this issue because this is not a problem of JD-GUI.

**Comment by samrocketman** [comment]
Perhaps give it the `enhancement` label?  Good to label issues so that you can keep track of feedback.

**Comment by chrylis** [comment]
I would like to also request some ability to display synthetics. In my case, I'm working with Groovy AST transformations that add and modify class members, and I want to be able to confirm that the results are correct. The proper behavior is to mark generated members as synthetic, but then I have to sort through `javap` output instead of being able to examine them in JD-GUI.

**Comment by LanderlYoung** [comment]
JD-GUI is a wonderful tool to discover what the compiler(java, groovy, kotlin, scala, etc...) is doing under the hood. But those compilers often generate synthetic methods, maybe it's a good idea to add an option in preference pannel?
