### ISSUE TITLE
FastCodeExceptionAnalyzer fooled into TYPE_ECLIPSE_677_CATCH_FINALLY because of nested empty catch

### ISSUE THREAD

**Issue by bgandon** [java-decompiler/jd-gui#80]
I investigated on a bug of jd-core 0.7.1 when disassembling the `LoadSingleClass(Loader, String)` method of `ClassFileDeserializer.class` from jd-core 0.7.1 itself (I just grabbed the jar from the mvn repo).

The problem is that `FastCodeExceptionAnalyzer.DefineType()` is fooled into the `TYPE_ECLIPSE_677_CATCH_FINALLY` just because of the **nested** empty catch, that introduces an `athrow` instruction.

Then things go wrong in `ComputeAfterOffset()`. When it looks for the `ALOAD`-`ATHROW` combination, the (previously detected) `ATHROW` is actually never found. This is due to the `AddCheckCastVisitor` that has added a `CHECKCAST` so that the combination is actually `ALOAD`-`CHECKCAST`-`ATHROW`.

But `ComputeAfterOffset()` is not prepared to not finding the expected `ALOAD`-`ATHROW`. Right after this, when doing `index += delta + 1`, it goes over the end of the method code, which leads to an `IndexOutOfBoundsException`.

I can help you with a junit test case I have written on this.

**Comment by emmanue1** [comment]
The recognition of "try-catch-finally" statements, in JD-Core 0.7.1, looks like a labyrinth. This part of code became unmaintainable. I'm working on new decompiler.
Thanks for this feedback. I close this issue : this is not a GUI bug.
