### ISSUE TITLE
using jd-gui in console mode

### ISSUE THREAD

**Issue by rshmelev** [java-decompiler/jd-gui#91]
Hi, i'm old jd-gui fan and would like to ask is there any possibility to run jd-gui in console mode like:

java -jar jd-gui-x.y.z.jar --console-mode --input=file.jar --output=decompiled.zip

Thanks for nice decompiler!

**Comment by ccarpenter04** [comment]
I support this and would like to see this feature added too, although with a different syntax. If I wrote a patch would emmanue1 accept it into the main branch?

**Comment by ccarpenter04** [comment]
Now that I think about it, this is JD-GUI so I could understand him not wanting to include a command line usage. JD-Core is the main decompiler and that would be a better place for it. Better yet though, a dedicated JD-CLI would make things much simpler. I'd be willing to work on any of these.

**Comment by emmanue1** [comment]
It's really esay to create a CLI now. Take a look here : Try last release, please. 2015 -> I close this issue.
2015 -> I close this issue.

**Comment by PaynMusic** [comment]
Being a stubborn person, very untrusting of software i've not heard of or thoroughly researched for trust issues. I am here to perhaps have this opened again. I am a developer that is working on software able to fully analyze electronic data, and parse from, save, or create a branch from original content. I would like to include jd-gui for assisted handling of jar and java files.
jd_gui_command = ["java", "-jar", jd_gui_path, "-d", output_directory, class_file_path]
returns -d as file not found. however it is supposed to be a command line operator to save sources to the output directory. i've seen other JD softwares available, but i dont want them. any help aside from suggesting some other decompiler would be great.
