### ISSUE TITLE
Internal Error for abstract inner class 

### ISSUE THREAD

**Issue by patstuart** [java-decompiler/jd-gui#93]
JD-GUI is failing when there is an abstract inner class.

To reproduce:
- Go to http://grepcode.com/snapshot/repo1.maven.org/maven2/com.sun.jersey/jersey-server/1.0/ and download the binary.
- Load the most recent version of JD-GUI (1.4.0 / 0.7.1)
- Attempt to load class `com.sun.jersey.server.impl.modelapi.validation.BasicValidator`.
- Observer the error message:  `// INTERNAL ERROR //`
- The above error message is duplicated when attempting to save all sources.

The source for the class is here: http://grepcode.com/file/repo1.maven.org/maven2/com.sun.jersey/jersey-server/1.0/com/sun/jersey/impl/modelapi/validation/BasicValidator.java?av=f

**Comment by emmanue1** [comment]
Fixed with last release. JD-GUI 1.5.0.
