### ISSUE TITLE
Can not decompile synthetic members, ENUM, while() and operator new some time.

### ISSUE THREAD

**Issue by GisTom2** [java-decompiler/jd-gui#95]
see files as examples, please.
Thanks!
save file as "baddecoding.zip" to open in zip

![baddecoding zip](https://cloud.githubusercontent.com/assets/15816029/11117871/08d58996-8946-11e5-9490-d1e46e40751e.png)

**Comment by emmanue1** [comment]
2015 -> I close this issue.
