### ISSUE TITLE
UI Freeze

### ISSUE THREAD

**Issue by aliveli186** [java-decompiler/jd-gui#96]
UI freezes and becomes unresponsive when I open 12 related jar files of total size of 107 mb.

**Comment by samrocketman** [comment]
How are you opening it?  Could you perhaps give JD GUI more memory to handle the larger files?  e.g. if you were using the platform independent JAR that would look something like this...

```bash
java -Xms4g -Xmx4g -XX:MaxPermSize=128M -jar jd-gui-x.y.z.jar
```

You also didn't provide enough information in your issue.  When opening an issue for any project I recommend you provide the following information:

* Your OS and architecture
* Java version and architecture.
* Software version of JD GUI.

**Comment by aliveli186** [comment]
I just drag the files over JD GUI and then open the search window Ctrl + Shift + S.
Actually the searching freezes the UI to be more specific.

**OS**: Microsoft Windows [Version 10.0.10586]

**Java Version**:
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) Client VM (build 25.66-b18, mixed mode)

**JD-GUI**: 1.4.0
**JD-CORE**: 0.7.1

**Comment by aliveli186** [comment]
`java -Xmx1024M -Xms1024M -jar jd-gui-1.4.0.jar`

worked.

**Comment by samrocketman** [comment]
Glad that it worked.  Seems it was an issue with JVM not having enough memory.  Not a big with JD GUI.
